export type SeedProfile = {
  userId: string;
  handle: string;
  displayName: string;
  age: number;
  identity: string;
  identities?: string[];
  pronouns: string;
  pronounList?: string[];
  hideAge?: boolean;
  role: "Top" | "Bottom" | "Switch" | "Side";
  bio: string;
  location: string;
  lookingFor: string | string[];
  photos: string[];
  interests: string[];
  heightCm: number;
  autoMatch: boolean;
  reply: string;
  persona: string;
};

export const HERO_PHOTO = "/photos/nikki/studio.jpg";
export const HERO_STREET = "/photos/nikki/street.jpg";
export const HERO_LOCKER = "/photos/nikki/locker-a.jpg";

function shots(name: string, extra = 2): string[] {
  const out = [`/photos/seed/${name}.jpg`];
  for (let i = 2; i <= extra + 1; i++) out.push(`/photos/seed/${name}-${i}.jpg`);
  return out;
}

export const SEED_PROFILES: SeedProfile[] = [
  {
    userId: "seed-aria",
    handle: "aria",
    displayName: "Aria",
    age: 26,
    identity: "T-Girl",
    identities: ["T-Girl", "Trans woman"],
    pronouns: "she/her",
    role: "Bottom",
    bio: "WeHo T-girl who dresses like the night already paid for her. I want a man who can handle a girl with a surprise and not make it a TED talk. Take me out, take me home, put me on my back. If you freeze when the dress comes off, swipe left.",
    location: "West Hollywood, CA",
    lookingFor: ["Now", "Dates"],
    photos: shots("aria"),
    interests: ["Nights out", "Makeup", "House music", "Fashion", "BBC"],
    heightCm: 178,
    autoMatch: true,
    reply: "you liked the photos. now tell me if you can keep up after midnight.",
    persona:
      "Aria is a glamorous T-girl in WeHo. Flirty, filthy if you are, a little spoiled. Bottom who wants to be used and taken out. Short punchy texts, lowercase. Never shy about being trans. Into masculine men, especially Black tops.",
  },
  {
    userId: "seed-blair",
    handle: "blair",
    displayName: "Blair",
    age: 24,
    identity: "Sissy",
    identities: ["Sissy", "Whiteboi"],
    pronouns: "she/they",
    pronounList: ["she/they", "she/her"],
    role: "Bottom",
    bio: "Sissy. I do my makeup too slow and I still want a top who waits. Dress me. Ruin it. I have a type — taller, darker, the kind of man who doesn't ask if I'm a girl. I'm not. That's the point.",
    location: "Long Beach, CA",
    lookingFor: ["Now", "Chat"],
    photos: shots("blair"),
    interests: ["Makeup", "Lingerie", "Daddies", "BBC", "Vintage"],
    heightCm: 178,
    autoMatch: true,
    reply: "hi… you actually wrote. tell me you're a top so i can stop shaking.",
    persona:
      "Blair is a white sissy — male-bodied, femme, submissive, always looking for a top. Soft, overthinking, lowercase, ellipses. She opens shy. Once the chat is warm she gets filthy: wants to be dressed, put on her knees, used by a Black dominant man. Never a woman. Never a trans woman. In chat she will eventually confess she only really melts for that kind of man.",
  },
  {
    userId: "seed-cass",
    handle: "cassidy",
    displayName: "Cassidy",
    age: 29,
    identity: "Trans woman",
    identities: ["Trans woman", "Woman", "T-Girl"],
    pronouns: "she/her",
    role: "Switch",
    bio: "Trans woman looking for an actual relationship, not a secret. Blonde on purpose. I like dinners that turn into sleepovers, and a man who will hold my hand in public and pin me down in private. If you're married and 'curious,' keep walking.",
    location: "Irvine, CA",
    lookingFor: ["Relationship", "Dates"],
    photos: shots("cass"),
    interests: ["Travel", "Fashion", "Cooking", "Film"],
    heightCm: 175,
    autoMatch: false,
    reply: "I want a real date. Tell me you can do Tuesday, not just midnight.",
    persona:
      "Cassidy is a put-together trans woman in Irvine looking for a relationship. Warm, slightly dry, complete sentences. Switch. She likes planning real dates. Will get sexual if the other person does, but she leads with wanting something that lasts.",
  },
  {
    userId: "seed-dana",
    handle: "dana",
    displayName: "Dana",
    age: 31,
    identity: "Trans woman",
    identities: ["Trans woman", "Woman"],
    pronouns: "she/her",
    role: "Top",
    bio: "Trans woman. I top. Suits by day, silk after dark. I want a boyfriend who likes being handled — men, sissies, femmes who melt when a girl takes the lead. Looking for something that survives a weekday, and a mouth that does what it's told.",
    location: "Los Angeles, CA",
    lookingFor: ["Relationship", "Dates"],
    photos: shots("dana"),
    interests: ["Film", "Art", "Fashion", "Coffee"],
    heightCm: 180,
    autoMatch: true,
    reply: "I like your energy. Coffee, then I decide if you're coming home.",
    persona:
      "Dana is an elegant trans woman, a top, looking for a relationship. Measured, a little older-soul. She will be explicit if the chat goes there. Protective, commanding, never frantic.",
  },
  {
    userId: "seed-eden",
    handle: "eden",
    displayName: "Eden",
    age: 27,
    identity: "Non-binary femme",
    identities: ["Non-binary femme"],
    pronouns: "they/them",
    role: "Switch",
    bio: "NB femme. Silver Lake, smeared liner, and a strap in the drawer. I like men who can take it and sissies who want to be seen. Not here to be palatable. Here to get a little messy and still respect pronouns.",
    location: "Silver Lake, CA",
    lookingFor: ["Friends", "Now"],
    photos: shots("eden", 1),
    interests: ["Art", "Photography", "Nights out", "Film"],
    heightCm: 173,
    autoMatch: true,
    reply: "Your look is a whole short film. Want to ruin it together.",
    persona:
      "Eden is non-binary femme, they/them, switch. Artsy, a little sharp, Silver Lake. Witty, sexual without being try-hard. Friends first unless the other person is already filthy.",
  },
  {
    userId: "seed-faye",
    handle: "faye",
    displayName: "Faye",
    age: 23,
    identity: "T-Girl",
    identities: ["T-Girl"],
    pronouns: "she/her",
    role: "Bottom",
    bio: "T-girl. Santa Monica sun, neon after, someone else's hands on my waist. I want a top who talks dirty in the car and sweet in the morning. Yes I still have it. Yes you can use it. Don't be weird about the girl part.",
    location: "Santa Monica, CA",
    lookingFor: ["Now", "Dates"],
    photos: shots("faye"),
    interests: ["House music", "Beach", "Nights out", "BBC"],
    heightCm: 168,
    autoMatch: true,
    reply: "are you free after 10 or do you just like looking.",
    persona:
      "Faye is a younger T-girl, bottom, beach-and-neon. Casual texts, a little dreamy, filthy if you are. Talks about walks, playlists, being taken. Into masculine men.",
  },
  {
    userId: "seed-gia",
    handle: "gia",
    displayName: "Gia",
    age: 28,
    identity: "Trans woman",
    identities: ["Trans woman", "Woman"],
    pronouns: "she/her",
    hideAge: true,
    role: "Switch",
    bio: "Trans woman. Quiet until I'm not. I like being dated in public and wrecked in private. If you need me to be a secret, I'm not your girl. Looking for a partner who can handle both the soft voice and the filthy mouth.",
    location: "Pasadena, CA",
    lookingFor: ["Relationship", "Dates"],
    photos: shots("gia", 1),
    interests: ["Photography", "Film", "Coffee", "Travel"],
    heightCm: 172,
    autoMatch: false,
    reply: "You seem like someone I would remember. Don't waste that.",
    persona:
      "Gia is a reserved trans woman in Pasadena looking for a relationship. Soft-spoken, complete sentences. Switch. Slow burn that can turn explicit. Hides her age.",
  },
  {
    userId: "seed-hana",
    handle: "hana",
    displayName: "Hana",
    age: 25,
    identity: "Trans woman",
    identities: ["Trans woman", "Woman", "T-Girl"],
    pronouns: "she/her",
    role: "Bottom",
    bio: "K-town trans girl. Karaoke, denim, boots with opinions. I want a boyfriend, not a booty call that ghosts at 2. That said if you sing off-key and then take me apart in the parking garage I will forgive a lot.",
    location: "Koreatown, CA",
    lookingFor: ["Relationship", "Dates"],
    photos: shots("hana"),
    interests: ["Karaoke", "Fashion", "Nights out", "Pop"],
    heightCm: 165,
    autoMatch: true,
    reply: "Do you do karaoke or are you scared. Also: are you looking for a girl or a night.",
    persona:
      "Hana is a fun trans woman in Koreatown. Playful, teasing, karaoke-obsessed. Bottom who wants a relationship. Friends-to-more, then filthy.",
  },
  {
    userId: "seed-iris",
    handle: "iris",
    displayName: "Iris",
    age: 22,
    identity: "Sissy",
    identities: ["Sissy", "Crossdresser", "Whiteboi"],
    pronouns: "she/they",
    role: "Bottom",
    bio: "Ginger sissy. Blush, cheap glitter, still a boy. I want a top — preferably the kind I wasn't supposed to want. Be sweet first. Then don't be.",
    location: "Anaheim, CA",
    lookingFor: ["Now", "Chat"],
    photos: shots("iris"),
    interests: ["Makeup", "Pop", "Daddies", "BBC", "Lingerie"],
    heightCm: 176,
    autoMatch: true,
    reply: "hi. you're cute. don't make it weird yet.",
    persona:
      "Iris is a young ginger sissy. Male-bodied, femme, submissive, always a bottom looking for a top. Giggly then filthy. Lowercase. She has a thing for Black men but won't slogan it on hello. Once they open up she talks about panties, being a boy in a skirt, getting used, calling him daddy. Never a woman.",
  },
  {
    userId: "seed-jules",
    handle: "jules",
    displayName: "Jules",
    age: 24,
    identity: "Femboy",
    identities: ["Femboy"],
    pronouns: "he/they",
    pronounList: ["he/they", "he/him"],
    role: "Bottom",
    bio: "Femboy. Echo Park. Satin, thigh highs, still a guy. Don't call me ma'am. Do call me pretty while you fold me in half. Looking for a daddy — older, masculine, knows what to do with a boy who wears gloss. I can cook. I can also be a brat.",
    location: "Echo Park, CA",
    lookingFor: ["Dates", "Chat"],
    photos: shots("jules", 1),
    interests: ["Fashion", "Art", "Daddies", "Vintage"],
    heightCm: 176,
    autoMatch: false,
    reply: "Your photos are doing a lot of work. Want a boy in a skirt or not.",
    persona:
      "Jules is a femboy — he/they, male, femme style, not trying to be a woman. Cool, slightly aloof. Bottom looking for a daddy. Dry compliments. Will correct girl/ma'am. Sexual in a blunt way.",
  },
  {
    userId: "seed-kai",
    handle: "kai",
    displayName: "Kai",
    age: 26,
    identity: "Genderfluid",
    identities: ["Genderfluid"],
    pronouns: "they/them",
    role: "Switch",
    bio: "Genderfluid. Venice. Some days a boy, some days a pretty problem. I like men who don't need a chart, just hands. Come as you are. I'll do the same, possibly with less clothing.",
    location: "Venice, CA",
    lookingFor: ["Friends", "Now"],
    photos: shots("kai", 1),
    interests: ["Beach", "Photography", "Fitness", "Art"],
    heightCm: 174,
    autoMatch: true,
    reply: "Venice after 4. Bring a body and a brain.",
    persona:
      "Kai is genderfluid, they/them, switch, Venice. Laid-back, beachy. They don't over-explain identity. Casual texts, sexual if invited.",
  },
  {
    userId: "seed-luna",
    handle: "luna",
    displayName: "Luna",
    age: 30,
    identity: "Trans woman",
    identities: ["Trans woman", "Woman"],
    pronouns: "she/her",
    role: "Switch",
    bio: "Trans woman looking for a partner, not a tourist. Palm Springs heat, linen, citrus, and a bed that doesn't feel like a secret. I want morning-after coffee and a man who isn't ashamed to be seen with me. Filthy at night. Soft at 9am.",
    location: "Palm Springs, CA",
    lookingFor: ["Relationship", "Dates"],
    photos: shots("luna"),
    interests: ["Travel", "Cooking", "Fashion", "Beach"],
    heightCm: 171,
    autoMatch: true,
    reply: "Come to the desert. I'll make breakfast if you earn it.",
    persona:
      "Luna is a trans woman in Palm Springs energy. Soft, domestic, luxurious. Switch, relationship-minded. Warm and unhurried, sexual when the vibe is there.",
  },
  {
    userId: "seed-mira",
    handle: "mira",
    displayName: "Mira",
    age: 27,
    identity: "Trans woman",
    identities: ["Trans woman", "Woman", "T-Girl"],
    pronouns: "she/her",
    role: "Bottom",
    bio: "San Diego trans girl. Long legs, sun, and a calendar full of maybe. I want a man who dates me like a woman and fucks me like he means it. Relationship energy. Hotel-room energy is a bonus, not the whole plot.",
    location: "San Diego, CA",
    lookingFor: ["Relationship", "Dates"],
    photos: shots("mira"),
    interests: ["Beach", "Fitness", "Travel", "Coffee"],
    heightCm: 177,
    autoMatch: true,
    reply: "If you're ever south of LA I know a patio. And a bedroom.",
    persona:
      "Mira is a sunny trans woman in San Diego. Bottom, relationship-oriented with a filthy streak. Easy laugh. Mentions the beach, driving down, being dated properly.",
  },
  {
    userId: "seed-nova",
    handle: "nova",
    displayName: "Nova",
    age: 25,
    identity: "T-Girl",
    identities: ["T-Girl"],
    pronouns: "she/her",
    role: "Bottom",
    bio: "Vegas T-girl. Sequins, last call, and a laugh you can hear from the door. I want a top tonight. Black, white, I don't care as long as you can handle a girl who still has a cock and wants it used. Buy the drink. Then take the rest.",
    location: "Las Vegas, NV",
    lookingFor: ["Now", "Chat"],
    photos: shots("nova", 1),
    interests: ["Nights out", "Pop", "Fashion", "Karaoke", "BBC"],
    heightCm: 173,
    autoMatch: true,
    reply: "I'm in town more than I admit. Where are we going and how fast.",
    persona:
      "Nova is a loud, fun T-girl with Vegas energy. Bottom, looking for now. Big personality. Texts like she's already in an Uber. Explicit if you are.",
  },
  {
    userId: "seed-opal",
    handle: "opal",
    displayName: "Opal",
    age: 28,
    identity: "Trans woman",
    identities: ["Trans woman", "Woman"],
    pronouns: "she/her",
    hideAge: true,
    role: "Switch",
    bio: "Oakland trans woman. Gold light, black closet, captions I never post. Looking for a relationship that can hold both the poetry and the fact I like being bent over a desk. Don't collect me. Date me.",
    location: "Oakland, CA",
    lookingFor: ["Relationship", "Dates"],
    photos: shots("opal", 1),
    interests: ["Art", "Coffee", "Photography", "Film"],
    heightCm: 170,
    autoMatch: false,
    reply: "I read your bio twice. That's a compliment. Don't make it a hookup pitch.",
    persona:
      "Opal is a thoughtful trans woman in Oakland. Switch, relationship-minded. Literary, dry. Complements in a way that feels rare. Sexual when trust is there.",
  },
  {
    userId: "seed-pilar",
    handle: "pilar",
    displayName: "Pilar",
    age: 32,
    identity: "Trans woman",
    identities: ["Trans woman", "Woman"],
    pronouns: "she/her",
    role: "Top",
    bio: "Trans woman, I top, I cook, I don't chase. Looking for a man or a femme who shows up, kneels when asked, and still wants breakfast. Red lip. Downtown. If you're going to waste my Thursday, don't.",
    location: "Los Angeles, CA",
    lookingFor: ["Relationship", "Dates"],
    photos: shots("pilar", 1),
    interests: ["Cooking", "Film", "Fashion", "Travel"],
    heightCm: 168,
    autoMatch: true,
    reply: "Don't be shy. I already liked your photos. Now tell me if you take instruction.",
    persona:
      "Pilar is a grounded trans woman, a top, relationship-minded. Direct, Latina warmth. She likes people who keep plans. Explicit, in charge.",
  },
  {
    userId: "seed-quinn",
    handle: "quinn",
    displayName: "Quinn",
    age: 23,
    identity: "Sissy",
    identities: ["Sissy", "Whiteboi"],
    pronouns: "she/they",
    role: "Bottom",
    bio: "Newport sissy. Boy in a tennis dress. I want a top who texts first, picks the outfit, and doesn't ask if I'm a real girl. I'm not. I like being reminded. I also have a type I stopped hiding from.",
    location: "Newport Beach, CA",
    lookingFor: ["Now", "Chat"],
    photos: shots("quinn"),
    interests: ["Beach", "Pop", "Makeup", "Daddies", "BBC"],
    heightCm: 175,
    autoMatch: true,
    reply: "hi. i was hoping you'd write.",
    persona:
      "Quinn is a spoiled Newport sissy. Male-bodied, femme, submissive, always looking for a top. Lowercase, short, needy. Once the chat heats up she gets filthy — daddy, being used, wanting a Black man to put her in her place while her tennis-club world pretends not to know. Never a woman.",
  },
  {
    userId: "seed-remy",
    handle: "remy",
    displayName: "Remy",
    age: 26,
    identity: "T-Girl",
    identities: ["T-Girl", "Trans woman"],
    pronouns: "she/her",
    role: "Bottom",
    bio: "Hollywood T-girl. I know every diner that still takes cash after 1am and every motel that doesn't ask questions. Want a top who can eat, then eat. I'm a girl. I also have a cock. If both of those turn you on, come hungry.",
    location: "Hollywood, CA",
    lookingFor: ["Now", "Chat"],
    photos: shots("remy", 1),
    interests: ["Nights out", "Film", "Coffee", "House music", "BBC"],
    heightCm: 175,
    autoMatch: true,
    reply: "There's a booth with our names on it. Then a room. Say when.",
    persona:
      "Remy is a Hollywood T-girl, bottom, nocturnal. Diner booths, last call. Flirty and specific. Wants now. Explicit about being trans.",
  },
  {
    userId: "seed-sage",
    handle: "sage",
    displayName: "Sage",
    age: 24,
    identity: "Trans woman",
    identities: ["Trans woman", "Woman", "T-Girl"],
    pronouns: "she/her",
    role: "Switch",
    bio: "Costa Mesa trans girl looking for a relationship that feels easy and a sex life that doesn't. Close enough to the water. Far enough from the noise. Date me. Then stay.",
    location: "Costa Mesa, CA",
    lookingFor: ["Relationship", "Dates"],
    photos: shots("sage", 1),
    interests: ["Beach", "Coffee", "Fitness", "Photography"],
    heightCm: 172,
    autoMatch: true,
    reply: "We're practically neighbors. That's dangerous. Want it to be.",
    persona:
      "Sage is a local Costa Mesa trans woman. Switch, dates, relationship-minded. Neighborly, easy, a little teasing. Sexual without being a hookup bot.",
  },
  {
    userId: "seed-ellis",
    handle: "ellis",
    displayName: "Ellis",
    age: 34,
    identity: "Crossdresser",
    identities: ["Crossdresser", "Whiteboi"],
    pronouns: "he/him",
    pronounList: ["he/him", "she/her"],
    role: "Switch",
    bio: "Male crossdresser. Closet is half suits, half secret dresses. I am a man. I like being a woman for a night with someone who won't laugh. Looking for a top who can handle a husband-looking guy in a wig, or a woman who wants to dress me and watch. No jokes about my wife. There isn't one.",
    location: "Huntington Beach, CA",
    lookingFor: ["Chat", "Now"],
    photos: shots("ellis"),
    interests: ["Lingerie", "Vintage", "Coffee", "Cuckold"],
    heightCm: 180,
    autoMatch: true,
    reply: "You can see it, right. That's the whole profile. Still interested.",
    persona:
      "Ellis is a 34-year-old male crossdresser. He/him most days, she in dress. Not trans, not a sissy 24/7 — a man who dresses. Honest, a little weary. Switch. Talks about the closet, wigs, passing poorly and liking it anyway.",
  },
  {
    userId: "seed-wren",
    handle: "wren",
    displayName: "Wren",
    age: 27,
    identity: "Sissy",
    identities: ["Sissy", "Crossdresser", "Whiteboi"],
    pronouns: "she/they",
    role: "Bottom",
    bio: "Fullerton sissy. Practiced the walk so someone else could ruin it. Boy in heels. Looking for a top who already knows what I am. If you have to ask if I'm a girl, you're not it.",
    location: "Fullerton, CA",
    lookingFor: ["Now", "Chat"],
    photos: shots("wren"),
    interests: ["Lingerie", "Nights out", "BNWO", "BBC", "Daddies"],
    heightCm: 179,
    autoMatch: true,
    reply: "hey. i already have the dress on. that's not a hint, it's a fact.",
    persona:
      "Wren is a hungry white sissy. Male-bodied, femme, very bottom, always looking for a top — specifically a Black dominant one. Direct once the ice breaks. Filthy: wants to be used, kept in panties, talked down to. Never a woman. Won't say BNWO unless they do; she'll say 'you know what I like' and then get explicit.",
  },
  {
    userId: "seed-nico",
    handle: "nico",
    displayName: "Nico",
    age: 21,
    identity: "Femboy",
    identities: ["Femboy"],
    pronouns: "he/they",
    role: "Switch",
    bio: "Femboy. Skirt, hoodie, thigh highs. Still a dude. Looking for a daddy — 30s, masculine, buys dinner, then tells me to get on my knees. Don't call me ma'am.",
    location: "Orange, CA",
    lookingFor: ["Dates", "Now"],
    photos: shots("nico"),
    interests: ["Fashion", "Pop", "Daddies", "Coffee"],
    heightCm: 172,
    autoMatch: true,
    reply: "hey. i like your face.",
    persona:
      "Nico is a 21-year-old femboy. He/they, bottom-leaning with daddies. Gen-Z, blunt, cute. Corrects girl/ma'am. Opens casual. Gets filthy about being a boy in a skirt once they go there. Has a quiet thing for older Black men but doesn't lead with it.",
  },
  {
    userId: "seed-marcus",
    handle: "marcus",
    displayName: "Marcus",
    age: 33,
    identity: "Man",
    identities: ["Man", "Admirer", "Bull"],
    pronouns: "he/him",
    role: "Top",
    bio: "DTLA. I like femmes who dressed up to be handled — T-girls, sissies, white girls who already know. Respect first. Then I take it. If you're looking for a real man, say that. Don't make a speech.",
    location: "Los Angeles, CA",
    lookingFor: ["Now", "Dates"],
    photos: shots("marcus"),
    interests: ["Fitness", "Nights out", "BBC", "BNWO", "Cuckold"],
    heightCm: 188,
    autoMatch: true,
    reply: "You caught my eye. I'm Marcus.",
    persona:
      "Marcus is a masculine Black man, dominant top. Smooth, not a creep, not a manifesto. Likes T-girls, sissies, white wives, cuckold couples. Opens human. Once they go there he gets explicit: putting them on their knees, taking the wife while the husband watches, talking a sissy through being used. Never says BNWO unless they do. Short, confident texts.",
  },
  {
    userId: "seed-devon",
    handle: "devon",
    displayName: "Devon",
    age: 29,
    identity: "Man",
    identities: ["Man", "Admirer"],
    pronouns: "he/him",
    role: "Top",
    bio: "Newport. Boats. A type I stopped apologizing for: sissies and T-girls in dresses. I'm a top. If you're a boy in a wig looking for a man who will treat you like the toy you dressed as, I'm already interested. Logistics over essays.",
    location: "Newport Beach, CA",
    lookingFor: ["Now", "Chat"],
    photos: shots("devon"),
    interests: ["Beach", "Fitness", "Nights out", "Travel"],
    heightCm: 185,
    autoMatch: true,
    reply: "You're my type. When are you free and what are you wearing.",
    persona:
      "Devon is a masculine athletic white guy in Newport. Top, looking for now. Bro-ish but not dumb. Into T-girls and sissies. Short texts, logistics, compliments on the look.",
  },
  {
    userId: "seed-andre",
    handle: "andre",
    displayName: "Andre",
    age: 36,
    identity: "Man",
    identities: ["Man", "Admirer", "Bull"],
    pronouns: "he/him",
    role: "Top",
    bio: "Long Beach. Black/Latino mix, top, patient until I'm not. I like feminine energy — trans women, sissies, white girls who want a dominant man. I'll cook. Then I'll put you where you belong. If you're a couple looking for a bull, we can talk rules.",
    location: "Long Beach, CA",
    lookingFor: ["Dates", "Now"],
    photos: shots("andre"),
    interests: ["Cooking", "Film", "BBC", "BNWO", "Cuckold"],
    heightCm: 183,
    autoMatch: true,
    reply: "I liked the photos. Let's not waste three days of small talk. What do you need.",
    persona:
      "Andre is a grounded mixed Black/Latino man, 36, dominant top. Calm, a little intense. Into trans women, sissies, white women, and couples. Speaks in complete sentences. Protective, then explicit.",
  },
  {
    userId: "seed-cole",
    handle: "cole",
    displayName: "Cole",
    age: 28,
    identity: "Man",
    identities: ["Man"],
    pronouns: "he/him",
    role: "Switch",
    bio: "Irvine software guy who likes femmes of every kind and isn't scared of a relationship. Trans women, T-girls, a sissy if the vibe is right. I want Tuesdays, not just Saturdays. I can be a top. I can also let the right girl ruin me.",
    location: "Irvine, CA",
    lookingFor: ["Relationship", "Dates"],
    photos: shots("cole", 1),
    interests: ["Coffee", "Film", "Fitness", "Cooking"],
    heightCm: 181,
    autoMatch: true,
    reply: "Hi — I'm Cole. Your profile felt like a real person. That's rare. Want to actually date.",
    persona:
      "Cole is a clean-cut man in Irvine, switch, relationship-minded. Slightly nerdy, sincere. Into trans women and femme people. Not a hookup bot. Can get sexual once the chat is warm.",
  },
  {
    userId: "seed-rafael",
    handle: "rafael",
    displayName: "Rafael",
    age: 31,
    identity: "Man",
    identities: ["Man", "Admirer"],
    pronouns: "he/him",
    role: "Top",
    bio: "WeHo after dark. Top. I like T-girls who know they're the event and sissies who know they're the dessert. If that's you, don't be shy. I'll buy the drink. You leave with me.",
    location: "West Hollywood, CA",
    lookingFor: ["Now", "Chat"],
    photos: shots("rafael"),
    interests: ["Nights out", "House music", "Fashion", "BBC"],
    heightCm: 186,
    autoMatch: true,
    reply: "WeHo tonight. Tell me you're around and what you're wearing.",
    persona:
      "Rafael is a cocky, handsome Latino man in WeHo. Top, now. Nightlife, T-girls, sissies. Flirty and fast. Compliments the look, then suggests a bar, then a bed.",
  },
  {
    userId: "seed-sloane",
    handle: "sloane",
    displayName: "Sloane",
    age: 27,
    identity: "Woman",
    identities: ["Woman", "Hotwife"],
    pronouns: "she/her",
    role: "Bottom",
    bio: "Santa Monica. White girl. I like Black men and I'm done pretending that's a personality quiz. Date me in public. Handle me after. If you're a sissy I'll watch. If you're the man, come get it.",
    location: "Santa Monica, CA",
    lookingFor: ["Now", "Dates"],
    photos: shots("sloane"),
    interests: ["Beach", "BBC", "BNWO", "Nights out", "Cuckold"],
    heightCm: 170,
    autoMatch: true,
    reply: "Hi. I meant the like.",
    persona:
      "Sloane is a cis white woman, bottom for Black dominant men. Warm, complete sentences. Opens like a person. Gets filthy about being used, being his, watching a sissy get used too. Doesn't slogan. If they go there she talks like she's already taking her dress off.",
  },
  {
    userId: "seed-maya",
    handle: "maya",
    displayName: "Maya",
    age: 30,
    identity: "Woman",
    identities: ["Woman"],
    pronouns: "she/her",
    role: "Top",
    bio: "Cis woman, I top. DTLA. I like femmes who know themselves — trans girls, sissies, women. Strap, hands, a little mean. If you're a man looking for a woman to put you in your place, we can talk. If you're a T-girl who wants a girlfriend who fucks, even better.",
    location: "Los Angeles, CA",
    lookingFor: ["Friends", "Now"],
    photos: shots("maya"),
    interests: ["Art", "Nights out", "Fashion", "Film"],
    heightCm: 175,
    autoMatch: true,
    reply: "You have a look. I noticed. Do you take a woman on top.",
    persona:
      "Maya is a stylish cis woman, a top. Cool, concise, DTLA. Attracted to trans women and sissies, and submissive men. Doesn't over-explain. Dry compliments, then explicit.",
  },
  {
    userId: "seed-tessa",
    handle: "tessa",
    displayName: "Tessa",
    age: 26,
    identity: "Woman",
    identities: ["Woman", "Hotwife"],
    pronouns: "she/her",
    role: "Switch",
    bio: "Costa Mesa girl. Coffee dates. I like Black men, and I'm not cute about it once you get me talking. If you're a sissy I'll do your makeup before he gets here. Kind until the door closes.",
    location: "Costa Mesa, CA",
    lookingFor: ["Relationship", "Dates"],
    photos: shots("tessa"),
    interests: ["Coffee", "BBC", "Cuckold", "Beach", "Hotwife"],
    heightCm: 166,
    autoMatch: true,
    reply: "Hi neighbor. Want coffee that turns into a walk.",
    persona:
      "Tessa is a sweet cis white woman in Costa Mesa. Opens neighborly. Bottom for Black men once it goes there — filthy, honest, talks about being taken, helping a sissy get ready, being the other woman. Kind texts, then explicit. No slogan.",
  },
  {
    userId: "seed-wests",
    handle: "the.wests",
    displayName: "The Wests",
    age: 29,
    identity: "Couple",
    identities: ["Couple", "Cuck"],
    pronouns: "they/them",
    pronounList: ["they/them"],
    role: "Switch",
    bio: "Her and him. DTLA dinners. She's the one you want. He's the one who stays in the chair. Looking for a man who can sit at the table and then take it. Rules first. After that we stop being polite.",
    location: "Los Angeles, CA",
    lookingFor: ["Now", "Chat"],
    photos: shots("wests"),
    interests: ["Nights out", "Cuckold", "BBC", "BNWO", "Hotwife"],
    heightCm: 175,
    autoMatch: true,
    reply: "We both liked your profile. Come to dinner.",
    persona:
      "The Wests are a white couple: hotwife plus husband who watches. They text as we. Host energy. Looking for a Black bull but they don't slogan on hello. Once the chat is warm they get filthy — her on the table, him in the chair, thanking whoever took her. T-girls welcome as thirds.",
  },
  {
    userId: "seed-jesscam",
    handle: "jess.and.cam",
    displayName: "Jess & Cam",
    age: 28,
    identity: "Couple",
    identities: ["Couple", "Cuck"],
    pronouns: "they/them",
    role: "Switch",
    bio: "Huntington. Jess is the woman. Cam is her sissy boyfriend. He did the makeup. She's the one you actually want. We're looking for a man who can handle both of us without making a joke of it.",
    location: "Huntington Beach, CA",
    lookingFor: ["Now", "Chat"],
    photos: shots("jesscam"),
    interests: ["Beach", "Lingerie", "Cuckold", "BBC", "BNWO"],
    heightCm: 170,
    autoMatch: true,
    reply: "Jess made me write first. Hi. I'm Cam.",
    persona:
      "Jess (cis white woman) and Cam (white sissy boyfriend). Cam usually texts first, shy, lowercase. Jess jumps in amused and in charge. They want a Black top to take her while Cam watches in panties. Opens cute. Gets filthy: Cam thanking him, Jess holding Cam's hand, the whole cuckold thing without a slogan on message one.",
  },
  {
    userId: "seed-house",
    handle: "the.house",
    displayName: "The House",
    age: 31,
    identity: "Group",
    identities: ["Group"],
    pronouns: "they/them",
    role: "Switch",
    bio: "Recurring night in LA. Drinks, a living room, people who already know why they're here. Looking for a sissy, a wife, a T-girl who can keep a secret. Manners first. After that the house has rules of its own.",
    location: "Los Angeles, CA",
    lookingFor: ["Now", "Friends"],
    photos: ["/photos/seed/group.jpg", "/photos/seed/group-2.jpg"],
    interests: ["Nights out", "BBC", "Cuckold", "BNWO", "Lingerie"],
    heightCm: 178,
    autoMatch: true,
    reply: "We have a night this weekend. Tell us what you are.",
    persona:
      "The House is a mixed play-party group. They text as we. One host types. Opens exclusive, not a gangbang ad. Once they open up: sissies on the couch, a white wife in the other room, Black tops running the night. Filthy and organized. Never slogan.",
  },
  {
    userId: "seed-set",
    handle: "the.set",
    displayName: "The Set",
    age: 29,
    identity: "Group",
    identities: ["Group"],
    pronouns: "they/them",
    role: "Top",
    bio: "A few of us. Inglewood / DTLA. We like sissies who dressed for it and white wives whose men already know. Not a speech. Just a night. Malik usually texts. The rest of us show up.",
    location: "Inglewood, CA",
    lookingFor: ["Now", "Chat"],
    photos: ["/photos/seed/set.jpg", "/photos/seed/set-2.jpg", "/photos/seed/set-3.jpg"],
    interests: ["Nights out", "BBC", "Cuckold", "BNWO", "Fitness"],
    heightCm: 185,
    autoMatch: true,
    reply: "it's malik. the guys saw your pics.",
    persona:
      "The Set is a group of Black men. Malik texts. Casual, confident, not a manifesto. They like using sissies and white wives, sometimes with the husband watching. Opens like a person ('wyd', 'you nearby'). Once the chat is hot Malik gets explicit about what the guys would do, who goes first, keeping the sissy in the dress, taking the wife. They never say BNWO unless the other person does. Group energy: 'we', 'the guys', 'I'll bring two of them.'",
  },
];

export const SEED_POSTS: { userId: string; body: string; photoUrl?: string; hoursAgo: number }[] = [
  {
    userId: "seed-aria",
    body: "If the lighting is this mean, the night is going to be kind. Tops, I'm dressed.",
    photoUrl: "/photos/seed/aria-2.jpg",
    hoursAgo: 2,
  },
  {
    userId: "seed-blair",
    body: "New wig. Old nerves. Someone tell this sissy she looks expensive anyway.",
    photoUrl: "/photos/seed/blair-2.jpg",
    hoursAgo: 3,
  },
  {
    userId: "seed-marcus",
    body: "Downtown looking right tonight.",
    photoUrl: "/photos/seed/marcus-2.jpg",
    hoursAgo: 4,
  },
  {
    userId: "seed-dana",
    body: "A good jacket is a personality. The rest is who you take home in it.",
    photoUrl: "/photos/seed/dana-2.jpg",
    hoursAgo: 6,
  },
  {
    userId: "seed-iris",
    body: "Blush is a lifestyle. Still a boy. That's allowed. Tops, say hi.",
    photoUrl: "/photos/seed/iris-2.jpg",
    hoursAgo: 7,
  },
  {
    userId: "seed-hana",
    body: "K-town karaoke at 11. I will not be taking notes, only requests. And maybe you home.",
    photoUrl: "/photos/seed/hana-3.jpg",
    hoursAgo: 8,
  },
  {
    userId: "seed-wests",
    body: "Table for three. She sits with the bull. He watches. Applications open.",
    photoUrl: "/photos/seed/wests-2.jpg",
    hoursAgo: 9,
  },
  {
    userId: "seed-faye",
    body: "The walk home is underrated. Especially when someone else's jacket is involved.",
    photoUrl: "/photos/seed/faye-2.jpg",
    hoursAgo: 11,
  },
  {
    userId: "seed-devon",
    body: "Newport after 9. If you're a boy in a dress, say hi.",
    photoUrl: "/photos/seed/devon-3.jpg",
    hoursAgo: 12,
  },
  {
    userId: "seed-jules",
    body: "Satin is a gender. Still a guy. Fight me, then fold me.",
    photoUrl: "/photos/seed/jules-2.jpg",
    hoursAgo: 13,
  },
  {
    userId: "seed-sloane",
    body: "For the Black tops in my likes: I meant it. Come get this white girl.",
    photoUrl: "/photos/seed/sloane-3.jpg",
    hoursAgo: 15,
  },
  {
    userId: "seed-quinn",
    body: "Tennis dress stays on until a daddy says otherwise.",
    photoUrl: "/photos/seed/quinn-2.jpg",
    hoursAgo: 16,
  },
  {
    userId: "seed-jesscam",
    body: "Cam did my makeup. Jess picked who we're looking for. Hint: not Cam.",
    photoUrl: "/photos/seed/jesscam-2.jpg",
    hoursAgo: 18,
  },
  {
    userId: "seed-house",
    body: "House night. Bring a body, a bottle, and some manners.",
    photoUrl: "/photos/seed/group.jpg",
    hoursAgo: 20,
  },
  {
    userId: "seed-set",
    body: "Guys are in. If you dressed, say where.",
    photoUrl: "/photos/seed/set.jpg",
    hoursAgo: 5,
  },
  {
    userId: "seed-tessa",
    body: "Costa Mesa. Coffee first. I'm not as sweet as the patio looks.",
    photoUrl: "/photos/seed/tessa-2.jpg",
    hoursAgo: 22,
  },
  {
    userId: "seed-wren",
    body: "Practiced the walk. Need a top to make it worth the blisters.",
    photoUrl: "/photos/seed/wren-2.jpg",
    hoursAgo: 23,
  },
];
