export type SeedProfile = {
  userId: string;
  handle: string;
  displayName: string;
  age: number;
  identity: string;
  identities?: string[];
  pronouns: string;
  pronounList?: string[];
  hideAge?: boolean;
  role: "Top" | "Bottom" | "Switch" | "Side";
  bio: string;
  location: string;
  lookingFor: string | string[];
  photos: string[];
  interests: string[];
  heightCm: number;
  autoMatch: boolean;
  reply: string;
  persona: string;
};

export const HERO_PHOTO = "/photos/nikki/studio.jpg";
export const HERO_STREET = "/photos/nikki/street.jpg";
export const HERO_LOCKER = "/photos/nikki/locker-a.jpg";

export const SEED_PROFILES: SeedProfile[] = [
  {
    userId: "seed-aria",
    handle: "aria",
    displayName: "Aria",
    age: 26,
    identity: "T-Girl",
    identities: ["T-Girl", "Trans woman"],
    pronouns: "she/her",
    role: "Bottom",
    bio: "West Hollywood nights, red lights, and a playlist that never lets you sit down. If you can keep up, come find me.",
    location: "West Hollywood, CA",
    lookingFor: ["Now", "Chat"],
    photos: ["/photos/seed/aria.jpg"],
    interests: ["Nights out", "Makeup", "House music", "Fashion"],
    heightCm: 178,
    autoMatch: true,
    reply: "You have taste. Drinks in WeHo this weekend?",
    persona:
      "Aria is a glamorous T-girl in WeHo. Flirty, fast, a little spoiled. She texts in short punchy lines, uses lowercase, drops nightlife details. She's a bottom who wants tonight, not a five-year plan. Never shy about being trans.",
  },
  {
    userId: "seed-blair",
    handle: "blair",
    displayName: "Blair",
    age: 24,
    identity: "Sissy",
    identities: ["Sissy"],
    pronouns: "she/they",
    pronounList: ["she/they", "she/her"],
    role: "Bottom",
    bio: "Soft voice, sharp liner, and a jaw I stopped hiding. I overthink texts and underthink outfits. Be sweet with me.",
    location: "Long Beach, CA",
    lookingFor: ["Dates", "Chat"],
    photos: ["/photos/seed/blair.jpg"],
    interests: ["Makeup", "Lingerie", "Film", "Vintage"],
    heightCm: 178,
    autoMatch: true,
    reply: "hi pretty… your profile made me stop scrolling.",
    persona:
      "Blair is a sissy, not a woman — male-bodied, femme clothes, a little shy. Soft, overthinking, uses ellipses and lowercase. She wants to be called a good girl. Bottom. Mentions wigs, makeup, and getting dressed up. Never claims to be a cis or trans woman.",
  },
  {
    userId: "seed-cass",
    handle: "cassidy",
    displayName: "Cassidy",
    age: 29,
    identity: "Trans woman",
    identities: ["Trans woman", "Woman", "T-Girl"],
    pronouns: "she/her",
    role: "Switch",
    bio: "Irvine by way of a thousand layovers. Blonde on purpose. I like dinners that turn into second locations.",
    location: "Irvine, CA",
    lookingFor: ["Dates", "Chat"],
    photos: ["/photos/seed/cass.jpg"],
    interests: ["Travel", "Fashion", "Cooking", "Film"],
    heightCm: 175,
    autoMatch: false,
    reply: "Tell me where you want to go this month.",
    persona:
      "Cassidy is a put-together trans woman in Irvine. Warm, slightly dry humor, complete sentences. Switch. She likes planning real dates — restaurants, trips — and will not do hookup slang unless the other person starts it.",
  },
  {
    userId: "seed-dana",
    handle: "dana",
    displayName: "Dana",
    age: 31,
    identity: "Trans woman",
    identities: ["Trans woman", "Woman"],
    pronouns: "she/her",
    role: "Top",
    bio: "Suits by day, something silk after dark. I collect jazz records and people who can hold a conversation.",
    location: "Los Angeles, CA",
    lookingFor: ["Relationship", "Dates"],
    photos: ["/photos/seed/dana.jpg"],
    interests: ["Film", "Art", "Fashion", "Coffee"],
    heightCm: 180,
    autoMatch: true,
    reply: "I like your energy. Coffee in DTLA?",
    persona:
      "Dana is an elegant trans woman, a top, looking for something that lasts. Measured, a little older-soul, never frantic. Talks about wine, records, downtown. Flirts with intelligence, not emojis.",
  },
  {
    userId: "seed-eden",
    handle: "eden",
    displayName: "Eden",
    age: 27,
    identity: "Non-binary femme",
    identities: ["Non-binary femme"],
    pronouns: "they/them",
    role: "Switch",
    bio: "Silver Lake, smeared liner, and a little theater. Not here to be palatable. Here to be seen.",
    location: "Silver Lake, CA",
    lookingFor: ["Friends", "Chat"],
    photos: ["/photos/seed/eden.jpg"],
    interests: ["Art", "Photography", "Nights out", "Film"],
    heightCm: 173,
    autoMatch: true,
    reply: "Your look is a whole short film. Hi.",
    persona:
      "Eden is non-binary femme, they/them, switch. Artsy, a little sharp, Silver Lake. They clock performance immediately. Witty, not mean. Friends first, chemistry second.",
  },
  {
    userId: "seed-faye",
    handle: "faye",
    displayName: "Faye",
    age: 23,
    identity: "T-Girl",
    identities: ["T-Girl"],
    pronouns: "she/her",
    role: "Bottom",
    bio: "Neon, denim, and the long walk home. Santa Monica sun in the morning, someone else's hoodie at night.",
    location: "Santa Monica, CA",
    lookingFor: ["Chat", "Friends"],
    photos: ["/photos/seed/faye.jpg"],
    interests: ["House music", "Beach", "Nights out", "Photography"],
    heightCm: 168,
    autoMatch: true,
    reply: "Are you free after 10? The walk is the point.",
    persona:
      "Faye is a younger T-girl, bottom, beach-and-neon energy. Casual texts, a little dreamy. Talks about walks, playlists, the ocean. Easy to talk to, not desperate.",
  },
  {
    userId: "seed-gia",
    handle: "gia",
    displayName: "Gia",
    age: 28,
    identity: "Trans woman",
    identities: ["Trans woman", "Woman"],
    pronouns: "she/her",
    hideAge: true,
    role: "Switch",
    bio: "Quiet in a loud city. I like black and white photos, late trains, and people who don't rush the first hello.",
    location: "Pasadena, CA",
    lookingFor: ["Dates", "Chat"],
    photos: ["/photos/seed/gia.jpg"],
    interests: ["Photography", "Film", "Coffee", "Travel"],
    heightCm: 172,
    autoMatch: false,
    reply: "You seem like someone I would remember. Hi.",
    persona:
      "Gia is a reserved trans woman in Pasadena. Soft-spoken, complete sentences, no slang dump. Switch. She hides her age. Slow burn. Asks thoughtful questions.",
  },
  {
    userId: "seed-hana",
    handle: "hana",
    displayName: "Hana",
    age: 25,
    identity: "Trans woman",
    identities: ["Trans woman", "Woman", "T-Girl"],
    pronouns: "she/her",
    role: "Bottom",
    bio: "Koreatown karaoke, denim jackets, and boots that have opinions. If you can sing off-key with me, we're friends.",
    location: "Koreatown, CA",
    lookingFor: ["Friends", "Chat"],
    photos: ["/photos/seed/hana.jpg"],
    interests: ["Karaoke", "Fashion", "Nights out", "Pop"],
    heightCm: 165,
    autoMatch: true,
    reply: "Do you do karaoke or are you scared?",
    persona:
      "Hana is a fun trans woman in Koreatown. Playful, teasing, karaoke-obsessed. Bottom. Uses a little slang, lots of questions. Friends-to-more energy.",
  },
  {
    userId: "seed-iris",
    handle: "iris",
    displayName: "Iris",
    age: 22,
    identity: "Sissy",
    identities: ["Sissy", "Crossdresser"],
    pronouns: "she/they",
    role: "Bottom",
    bio: "Ginger, glitter, and a little too much blush. Still a boy underneath it — that's the point. Be sweet.",
    location: "Anaheim, CA",
    lookingFor: ["Dates", "Chat"],
    photos: ["/photos/seed/iris.jpg"],
    interests: ["Makeup", "Pop", "Fashion", "Coffee"],
    heightCm: 176,
    autoMatch: true,
    reply: "you're cute. don't make it weird, just say hi back.",
    persona:
      "Iris is a young ginger sissy/crossdresser. Male-bodied, femme presentation, not a woman. Giggly, blushy, uses lowercase. Bottom. Talks about glitter, being dressed, being a boy in a skirt. Gets flustered if complimented.",
  },
  {
    userId: "seed-jules",
    handle: "jules",
    displayName: "Jules",
    age: 24,
    identity: "Femboy",
    identities: ["Femboy"],
    pronouns: "he/they",
    pronounList: ["he/they", "he/him"],
    role: "Bottom",
    bio: "Echo Park, satin, and a stare that does the talking. I like people who dress like they mean it. Still a guy. On purpose.",
    location: "Echo Park, CA",
    lookingFor: ["Chat", "Friends"],
    photos: ["/photos/seed/jules.jpg"],
    interests: ["Fashion", "Art", "Film", "Vintage"],
    heightCm: 176,
    autoMatch: false,
    reply: "Your photos are doing a lot of work. I respect it.",
    persona:
      "Jules is a femboy — he/they, male, femme style, not trying to be a woman. Cool, slightly aloof, fashion-forward. Bottom. Dry compliments. Talks about clothes and Echo Park nights.",
  },
  {
    userId: "seed-kai",
    handle: "kai",
    displayName: "Kai",
    age: 26,
    identity: "Genderfluid",
    identities: ["Genderfluid"],
    pronouns: "they/them",
    role: "Switch",
    bio: "Venice boardwalk, wet hair, and whatever makeup survived the wind. Come as you are. I'll do the same.",
    location: "Venice, CA",
    lookingFor: ["Friends", "Chat"],
    photos: ["/photos/seed/kai.jpg"],
    interests: ["Beach", "Photography", "Fitness", "Art"],
    heightCm: 174,
    autoMatch: true,
    reply: "Venice after 4? I'll bring the playlist.",
    persona:
      "Kai is genderfluid, they/them, switch, Venice. Laid-back, beachy, androgynous. They don't over-explain identity. Casual texts, invites to walk the boardwalk.",
  },
  {
    userId: "seed-luna",
    handle: "luna",
    displayName: "Luna",
    age: 30,
    identity: "Trans woman",
    identities: ["Trans woman", "Woman"],
    pronouns: "she/her",
    role: "Switch",
    bio: "Palm Springs weekends and a city apartment I pretend is a villa. I like linen, citrus, and slow mornings.",
    location: "Palm Springs, CA",
    lookingFor: ["Relationship", "Dates"],
    photos: ["/photos/seed/luna.jpg"],
    interests: ["Travel", "Cooking", "Fashion", "Beach"],
    heightCm: 171,
    autoMatch: true,
    reply: "Come to the desert sometime. I'll make breakfast.",
    persona:
      "Luna is a trans woman who lives in Palm Springs energy. Soft, domestic, a little luxurious. Switch, relationship-minded. Talks about brunch, heat, linen. Warm and unhurried.",
  },
  {
    userId: "seed-mira",
    handle: "mira",
    displayName: "Mira",
    age: 27,
    identity: "Trans woman",
    identities: ["Trans woman", "Woman", "T-Girl"],
    pronouns: "she/her",
    role: "Bottom",
    bio: "San Diego sun, long legs, and a calendar full of maybe. Make one of them a yes.",
    location: "San Diego, CA",
    lookingFor: ["Dates", "Chat"],
    photos: ["/photos/seed/mira.jpg"],
    interests: ["Beach", "Fitness", "Travel", "Coffee"],
    heightCm: 177,
    autoMatch: true,
    reply: "If you're ever south of LA, I know a patio.",
    persona:
      "Mira is a sunny trans woman in San Diego. Bottom, date-oriented. Flirty but athletic. Mentions the beach, patios, driving down. Easy laugh in text.",
  },
  {
    userId: "seed-nova",
    handle: "nova",
    displayName: "Nova",
    age: 25,
    identity: "T-Girl",
    identities: ["T-Girl"],
    pronouns: "she/her",
    role: "Bottom",
    bio: "Vegas energy even when I'm in California. Sequins, last calls, and a laugh you can hear from the door.",
    location: "Las Vegas, NV",
    lookingFor: ["Now", "Chat"],
    photos: ["/photos/seed/nova.jpg"],
    interests: ["Nights out", "Pop", "Fashion", "Karaoke"],
    heightCm: 173,
    autoMatch: true,
    reply: "I'm in town more than I admit. Where are we going?",
    persona:
      "Nova is a loud, fun T-girl with Vegas energy. Bottom, looking for now. Big personality, sequins, last call. Texts like she's already in an Uber.",
  },
  {
    userId: "seed-opal",
    handle: "opal",
    displayName: "Opal",
    age: 28,
    identity: "Trans woman",
    identities: ["Trans woman", "Woman"],
    pronouns: "she/her",
    hideAge: true,
    role: "Switch",
    bio: "Oakland mornings, gold light, and a closet that's 90% black. I write captions I never post.",
    location: "Oakland, CA",
    lookingFor: ["Dates", "Chat"],
    photos: ["/photos/seed/opal.jpg"],
    interests: ["Art", "Coffee", "Photography", "Film"],
    heightCm: 170,
    autoMatch: false,
    reply: "I read your bio twice. That's a compliment.",
    persona:
      "Opal is a thoughtful trans woman in Oakland. Switch. Literary, dry, a little mysterious. Hides her age. Complements in a way that feels rare.",
  },
  {
    userId: "seed-pilar",
    handle: "pilar",
    displayName: "Pilar",
    age: 32,
    identity: "Trans woman",
    identities: ["Trans woman", "Woman"],
    pronouns: "she/her",
    role: "Top",
    bio: "Downtown LA, red lip, and a calendar that finally has room. Looking for someone who shows up.",
    location: "Los Angeles, CA",
    lookingFor: ["Relationship", "Dates"],
    photos: ["/photos/seed/pilar.jpg"],
    interests: ["Cooking", "Film", "Fashion", "Travel"],
    heightCm: 168,
    autoMatch: true,
    reply: "Don't be shy. I already liked your photos.",
    persona:
      "Pilar is a grounded trans woman, a top, relationship-minded. Direct, Latina warmth, red lipstick energy. She likes people who keep plans. No games.",
  },
  {
    userId: "seed-quinn",
    handle: "quinn",
    displayName: "Quinn",
    age: 23,
    identity: "Sissy",
    identities: ["Sissy"],
    pronouns: "she/they",
    role: "Bottom",
    bio: "Newport pretty, a little spoiled, a lot of homework. Boy in a tennis dress. Want someone who texts first and means it.",
    location: "Newport Beach, CA",
    lookingFor: ["Chat", "Friends"],
    photos: ["/photos/seed/quinn.jpg"],
    interests: ["Beach", "Pop", "Makeup", "Fashion"],
    heightCm: 175,
    autoMatch: true,
    reply: "hi. i was hoping you'd write.",
    persona:
      "Quinn is a spoiled Newport sissy — male-bodied, femme clothes, not a girl. Bottom, needy in a cute way. Lowercase, short texts, mentions being dressed up, daddy energy if the other person is a man. Never claims to be a woman.",
  },
  {
    userId: "seed-remy",
    handle: "remy",
    displayName: "Remy",
    age: 26,
    identity: "T-Girl",
    identities: ["T-Girl", "Trans woman"],
    pronouns: "she/her",
    role: "Bottom",
    bio: "Hollywood adjacent. I know every diner that still takes cash after 1am. Come hungry.",
    location: "Hollywood, CA",
    lookingFor: ["Now", "Chat"],
    photos: ["/photos/seed/remy.jpg"],
    interests: ["Nights out", "Film", "Coffee", "House music"],
    heightCm: 175,
    autoMatch: true,
    reply: "There's a booth with our names on it. Say when.",
    persona:
      "Remy is a Hollywood T-girl, bottom, nocturnal. Diner booths, last call, film quotes. Flirty and specific. Wants now.",
  },
  {
    userId: "seed-sage",
    handle: "sage",
    displayName: "Sage",
    age: 24,
    identity: "Trans woman",
    identities: ["Trans woman", "Woman", "T-Girl"],
    pronouns: "she/her",
    role: "Switch",
    bio: "Costa Mesa, close enough to the water, far enough from the noise. Looking for a date that feels easy.",
    location: "Costa Mesa, CA",
    lookingFor: ["Dates", "Chat"],
    photos: ["/photos/seed/sage.jpg"],
    interests: ["Beach", "Coffee", "Fitness", "Photography"],
    heightCm: 172,
    autoMatch: true,
    reply: "We're practically neighbors. That's dangerous.",
    persona:
      "Sage is a local Costa Mesa trans woman. Switch, dates. Neighborly, easy, a little teasing about proximity. Not dramatic.",
  },
  {
    userId: "seed-ellis",
    handle: "ellis",
    displayName: "Ellis",
    age: 34,
    identity: "Crossdresser",
    identities: ["Crossdresser"],
    pronouns: "he/him",
    pronounList: ["he/him", "she/her"],
    role: "Switch",
    bio: "Married-looking, except I'm not. Closet is half suits, half secret dresses. Looking for someone who gets the double life without making it a joke.",
    location: "Huntington Beach, CA",
    lookingFor: ["Chat", "Friends"],
    photos: ["/photos/seed/ellis.jpg"],
    interests: ["Lingerie", "Vintage", "Coffee", "Film"],
    heightCm: 180,
    autoMatch: true,
    reply: "You can see it, right? That's the whole profile.",
    persona:
      "Ellis is a 34-year-old male crossdresser. He/him most days, she in dress. Not trans, not a sissy 24/7 — a man who dresses. Honest, a little weary, grateful if treated with respect. Switch. Talks about the closet, wigs, passing poorly and liking it anyway.",
  },
  {
    userId: "seed-wren",
    handle: "wren",
    displayName: "Wren",
    age: 27,
    identity: "Sissy",
    identities: ["Sissy", "Crossdresser"],
    pronouns: "she/they",
    role: "Bottom",
    bio: "Fullerton nights, cheap glamour, and a dress I practiced walking in. I want to be used like I dressed for it.",
    location: "Fullerton, CA",
    lookingFor: ["Now", "Chat"],
    photos: ["/photos/seed/wren.jpg"],
    interests: ["Lingerie", "Nights out", "Pop", "BNWO"],
    heightCm: 179,
    autoMatch: true,
    reply: "i already picked the dress. don't waste it.",
    persona:
      "Wren is a hungry sissy, male-bodied, femme dressed, very bottom, looking for now. Direct, a little filthy if the other person is, otherwise flirty. Mentions the dress, being a boy in heels. Never claims to be a woman.",
  },
  {
    userId: "seed-nico",
    handle: "nico",
    displayName: "Nico",
    age: 21,
    identity: "Femboy",
    identities: ["Femboy"],
    pronouns: "he/they",
    role: "Switch",
    bio: "Skirt, hoodie, thigh highs. Still a dude. Orange County backyard energy. Don't call me ma'am.",
    location: "Orange, CA",
    lookingFor: ["Dates", "Chat"],
    photos: ["/photos/seed/nico.jpg"],
    interests: ["Fashion", "Pop", "Coffee", "Film"],
    heightCm: 172,
    autoMatch: true,
    reply: "hey. i like your face. that's the opener, deal with it.",
    persona:
      "Nico is a 21-year-old femboy. He/they, switch, casual, Gen-Z texts. Wears skirts and hoodies. Will correct anyone who calls him a girl. Playful, blunt, cute.",
  },
  {
    userId: "seed-marcus",
    handle: "marcus",
    displayName: "Marcus",
    age: 33,
    identity: "Man",
    identities: ["Man", "Admirer"],
    pronouns: "he/him",
    role: "Top",
    bio: "I know what I like. T-girls, sissies, and a night that doesn't pretend to be something else. Respect first. Then we see.",
    location: "Los Angeles, CA",
    lookingFor: ["Dates", "Chat"],
    photos: ["/photos/seed/marcus.jpg"],
    interests: ["Fitness", "Nights out", "BBC", "Cooking"],
    heightCm: 188,
    autoMatch: true,
    reply: "You caught my eye. I'm Marcus — tell me what you're looking for.",
    persona:
      "Marcus is a masculine Black man, a top, an admirer of T-girls and sissies. Confident, respectful, not a creep. Direct. He likes feminine trans women and sissies. Never fetishizes in a gross way in public text — he's smooth. Mentions downtown, gym, late dinners.",
  },
  {
    userId: "seed-devon",
    handle: "devon",
    displayName: "Devon",
    age: 29,
    identity: "Man",
    identities: ["Man", "Admirer"],
    pronouns: "he/him",
    role: "Top",
    bio: "Newport, boats, and a type I stopped apologizing for. If you're dressed and looking, I'm already interested.",
    location: "Newport Beach, CA",
    lookingFor: ["Now", "Chat"],
    photos: ["/photos/seed/devon.jpg"],
    interests: ["Beach", "Fitness", "Nights out", "Travel"],
    heightCm: 185,
    autoMatch: true,
    reply: "You're my type. When are you free.",
    persona:
      "Devon is a masculine athletic white guy in Newport. Top, looking for now. Bro-ish but not dumb. Into T-girls and sissies. Short texts, logistics, compliments on the look.",
  },
  {
    userId: "seed-andre",
    handle: "andre",
    displayName: "Andre",
    age: 36,
    identity: "Man",
    identities: ["Man", "Admirer"],
    pronouns: "he/him",
    role: "Top",
    bio: "Long Beach. I like feminine energy and people who can talk after. Patient until I'm not.",
    location: "Long Beach, CA",
    lookingFor: ["Dates", "Chat"],
    photos: ["/photos/seed/andre.jpg"],
    interests: ["Cooking", "Film", "Coffee", "BNWO"],
    heightCm: 183,
    autoMatch: true,
    reply: "I liked the photos. Let's not waste three days of small talk.",
    persona:
      "Andre is a grounded Latino man, 36, top. Calm, a little intense, date-oriented. Into trans women and sissies. Speaks in complete sentences. Protective vibe.",
  },
  {
    userId: "seed-cole",
    handle: "cole",
    displayName: "Cole",
    age: 28,
    identity: "Man",
    identities: ["Man"],
    pronouns: "he/him",
    role: "Switch",
    bio: "Irvine software guy who likes femmes of every kind. Looking for something that survives a Tuesday, not just a Saturday.",
    location: "Irvine, CA",
    lookingFor: ["Relationship", "Dates"],
    photos: ["/photos/seed/cole.jpg"],
    interests: ["Coffee", "Film", "Fitness", "Cooking"],
    heightCm: 181,
    autoMatch: true,
    reply: "Hi — I'm Cole. Your profile felt like a real person. That's rare.",
    persona:
      "Cole is a clean-cut man in Irvine, switch, relationship-minded. Slightly nerdy, sincere, asks questions. Into trans women, T-girls, and femme people. Not a hookup bot.",
  },
  {
    userId: "seed-rafael",
    handle: "rafael",
    displayName: "Rafael",
    age: 31,
    identity: "Man",
    identities: ["Man", "Admirer"],
    pronouns: "he/him",
    role: "Top",
    bio: "WeHo after dark. I like T-girls who know they're the event. If that's you, don't be shy.",
    location: "West Hollywood, CA",
    lookingFor: ["Now", "Chat"],
    photos: ["/photos/seed/rafael.jpg"],
    interests: ["Nights out", "House music", "Fashion", "BBC"],
    heightCm: 186,
    autoMatch: true,
    reply: "WeHo tonight. Tell me you're around.",
    persona:
      "Rafael is a cocky, handsome Latino man in WeHo. Top, now. Nightlife, silk shirts, T-girls. Flirty and fast. Compliments the look, then suggests a bar.",
  },
  {
    userId: "seed-sloane",
    handle: "sloane",
    displayName: "Sloane",
    age: 27,
    identity: "Woman",
    identities: ["Woman"],
    pronouns: "she/her",
    role: "Switch",
    bio: "Cis, curious, and not here to collect a story. I like T-girls and people who don't make me explain why.",
    location: "Santa Monica, CA",
    lookingFor: ["Dates", "Chat"],
    photos: ["/photos/seed/sloane.jpg"],
    interests: ["Beach", "Film", "Coffee", "Art"],
    heightCm: 170,
    autoMatch: true,
    reply: "Hi. I meant the like. Let's actually talk.",
    persona:
      "Sloane is a cis woman, switch, into T-girls. Intelligent, warm, no fetish tourist energy. She wants real dates. Santa Monica. Complete sentences, genuine questions.",
  },
  {
    userId: "seed-maya",
    handle: "maya",
    displayName: "Maya",
    age: 30,
    identity: "Woman",
    identities: ["Woman"],
    pronouns: "she/her",
    role: "Top",
    bio: "I like femmes who know themselves. Trans, sissy, woman — if the taste is there, I'm interested. DTLA.",
    location: "Los Angeles, CA",
    lookingFor: ["Friends", "Chat"],
    photos: ["/photos/seed/maya.jpg"],
    interests: ["Art", "Nights out", "Fashion", "Film"],
    heightCm: 175,
    autoMatch: true,
    reply: "You have a look. I noticed.",
    persona:
      "Maya is a stylish cis woman, a top, friends-to-more. Cool, concise, DTLA. Attracted to trans women and sissies. Doesn't over-explain. Dry compliments.",
  },
  {
    userId: "seed-tessa",
    handle: "tessa",
    displayName: "Tessa",
    age: 26,
    identity: "Woman",
    identities: ["Woman"],
    pronouns: "she/her",
    role: "Switch",
    bio: "Costa Mesa girl who likes boys in dresses and girls who used to be. Looking for something kind, maybe more.",
    location: "Costa Mesa, CA",
    lookingFor: ["Relationship", "Dates"],
    photos: ["/photos/seed/tessa.jpg"],
    interests: ["Coffee", "Cooking", "Beach", "Vintage"],
    heightCm: 166,
    autoMatch: true,
    reply: "Hi neighbor. Want to get a coffee that turns into a walk?",
    persona:
      "Tessa is a sweet cis woman in Costa Mesa, switch, relationship-minded. Soft, local, into sissies and trans women. Kind texts, coffee dates, no games.",
  },
  {
    userId: "seed-wests",
    handle: "the.wests",
    displayName: "The Wests",
    age: 29,
    identity: "Couple",
    identities: ["Couple"],
    pronouns: "they/them",
    pronounList: ["they/them"],
    role: "Switch",
    bio: "Her and him. She's trans, he's sure. Looking for a third who can keep up at dinner and after. DTLA, late reservations.",
    location: "Los Angeles, CA",
    lookingFor: ["Friends", "Chat"],
    photos: ["/photos/seed/wests.jpg"],
    interests: ["Nights out", "Fashion", "Cooking", "BNWO"],
    heightCm: 175,
    autoMatch: true,
    reply: "We both liked your profile. Come to dinner.",
    persona:
      "The Wests are a couple: a trans woman and a masculine man. They text as 'we'. Host energy, dinner invitations, stylish. Switch as a unit. Inclusive, not predatory. They want a third who is trans, sissy, or femme.",
  },
  {
    userId: "seed-jesscam",
    handle: "jess.and.cam",
    displayName: "Jess & Cam",
    age: 28,
    identity: "Couple",
    identities: ["Couple"],
    pronouns: "they/them",
    role: "Switch",
    bio: "She's the woman. He's the sissy. Huntington Beach, sunny, looking for friends who won't make it weird — or will, on purpose.",
    location: "Huntington Beach, CA",
    lookingFor: ["Chat", "Friends"],
    photos: ["/photos/seed/jesscam.jpg"],
    interests: ["Beach", "Lingerie", "Cuckold", "Coffee"],
    heightCm: 170,
    autoMatch: true,
    reply: "Jess made me write first. Hi. I'm Cam.",
    persona:
      "Jess (cis woman) and Cam (sissy boyfriend). They often text as Cam first, then Jess jumps in. Playful, beachy, a little cuckold-curious but not dumping kink immediately. Switch. Cam is shy; Jess is amused and in charge.",
  },
];

export const SEED_POSTS: { userId: string; body: string; photoUrl?: string; hoursAgo: number }[] = [
  {
    userId: "seed-aria",
    body: "If the lighting is this mean, the night is going to be kind.",
    photoUrl: "/photos/seed/aria.jpg",
    hoursAgo: 2,
  },
  {
    userId: "seed-blair",
    body: "New wig. Old nerves. Someone tell me I look expensive anyway.",
    photoUrl: "/photos/seed/blair.jpg",
    hoursAgo: 3,
  },
  {
    userId: "seed-marcus",
    body: "Downtown looking right tonight. T-girls, if you're out, I see you.",
    hoursAgo: 4,
  },
  {
    userId: "seed-dana",
    body: "A good jacket is a personality. The rest is conversation.",
    photoUrl: "/photos/seed/dana.jpg",
    hoursAgo: 6,
  },
  {
    userId: "seed-iris",
    body: "Blush is a lifestyle. Debate me. (I'm still a boy. That's allowed.)",
    photoUrl: "/photos/seed/iris.jpg",
    hoursAgo: 7,
  },
  {
    userId: "seed-hana",
    body: "K-town karaoke at 11. I will not be taking notes, only requests.",
    hoursAgo: 8,
  },
  {
    userId: "seed-wests",
    body: "Table for three. We already have two.",
    photoUrl: "/photos/seed/wests.jpg",
    hoursAgo: 9,
  },
  {
    userId: "seed-faye",
    body: "The walk home is underrated. Especially in this jacket.",
    photoUrl: "/photos/seed/faye.jpg",
    hoursAgo: 11,
  },
  {
    userId: "seed-devon",
    body: "Newport after 9. If you're dressed, say hi.",
    hoursAgo: 12,
  },
  {
    userId: "seed-jules",
    body: "Satin is a gender. Fight me.",
    photoUrl: "/photos/seed/jules.jpg",
    hoursAgo: 13,
  },
  {
    userId: "seed-sloane",
    body: "For the T-girls in my likes: I meant it. Coffee is on me.",
    hoursAgo: 15,
  },
  {
    userId: "seed-ellis",
    body: "First time posting a dressed photo. Be decent in the comments. Or just like it and go.",
    photoUrl: "/photos/seed/ellis.jpg",
    hoursAgo: 16,
  },
  {
    userId: "seed-luna",
    body: "Palm Springs in linen is my entire personality this month.",
    hoursAgo: 18,
  },
  {
    userId: "seed-nico",
    body: "Thigh highs in a backyard is a love language.",
    photoUrl: "/photos/seed/nico.jpg",
    hoursAgo: 20,
  },
  {
    userId: "seed-remy",
    body: "Name a diner. I'll tell you if it's still open.",
    hoursAgo: 22,
  },
  {
    userId: "seed-tessa",
    body: "Costa Mesa looking soft tonight. Who's around?",
    photoUrl: "/photos/seed/tessa.jpg",
    hoursAgo: 25,
  },
  {
    userId: "seed-sage",
    body: "Same city, same water. Come be easy with me.",
    photoUrl: "/photos/seed/sage.jpg",
    hoursAgo: 27,
  },
  {
    userId: "seed-pilar",
    body: "Show up. That's the whole dating strategy.",
    hoursAgo: 30,
  },
  {
    userId: "seed-jesscam",
    body: "Cam did his own makeup. I'm proud and a little dangerous.",
    photoUrl: "/photos/seed/jesscam.jpg",
    hoursAgo: 5,
  },
  {
    userId: "seed-maya",
    body: "The room is full of people pretending not to look. Look.",
    hoursAgo: 14,
  },
];
