/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AppDiscoverRouteImport } from './routes/_app/discover'
import { Route as AppFeedRouteImport } from './routes/_app/feed'
import { Route as AppInboxRouteImport } from './routes/_app/inbox'
import { Route as AppLikesRouteImport } from './routes/_app/likes'
import { Route as AppMeRouteImport } from './routes/_app/me'
import { Route as ApiAppRouteImport } from './routes/api/app'
import { Route as ApiProfileRouteImport } from './routes/api/profile'
import { Route as AuthCompleteRouteImport } from './routes/auth.complete'
import { Route as AppInboxIndexRouteImport } from './routes/_app/inbox.index'
import { Route as AppInboxIdRouteImport } from './routes/_app/inbox.$id'
import { Route as AppUHandleRouteImport } from './routes/_app/u.$handle'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiEmailLoginRouteImport } from './routes/api/email/login'
import { Route as ApiMessagesListRouteImport } from './routes/api/messages/list'
import { Route as ApiMessagesOpenRouteImport } from './routes/api/messages/open'
import { Route as ApiMessagesReplyRouteImport } from './routes/api/messages/reply'
import { Route as ApiMessagesSendRouteImport } from './routes/api/messages/send'
import { Route as ApiMessagesThreadRouteImport } from './routes/api/messages/thread'
import { Route as ApiPhoneLoginRouteImport } from './routes/api/phone/login'
import { Route as ApiPhoneStartRouteImport } from './routes/api/phone/start'
import { Route as ApiSessionEnsureRouteImport } from './routes/api/session/ensure'
import { Route as ApiSessionLogoutRouteImport } from './routes/api/session/logout'
import { Route as ApiSessionTokenRouteImport } from './routes/api/session/token'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDiscoverRoute = AppDiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => AppRoute,
} as any)
const AppFeedRoute = AppFeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => AppRoute,
} as any)
const AppInboxRoute = AppInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AppRoute,
} as any)
const AppLikesRoute = AppLikesRouteImport.update({
  id: '/likes',
  path: '/likes',
  getParentRoute: () => AppRoute,
} as any)
const AppMeRoute = AppMeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => AppRoute,
} as any)
const ApiAppRoute = ApiAppRouteImport.update({
  id: '/api/app',
  path: '/api/app',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProfileRoute = ApiProfileRouteImport.update({
  id: '/api/profile',
  path: '/api/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCompleteRoute = AuthCompleteRouteImport.update({
  id: '/auth/complete',
  path: '/auth/complete',
  getParentRoute: () => rootRouteImport,
} as any)
const AppInboxIndexRoute = AppInboxIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppInboxRoute,
} as any)
const AppInboxIdRoute = AppInboxIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppInboxRoute,
} as any)
const AppUHandleRoute = AppUHandleRouteImport.update({
  id: '/u/$handle',
  path: '/u/$handle',
  getParentRoute: () => AppRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEmailLoginRoute = ApiEmailLoginRouteImport.update({
  id: '/api/email/login',
  path: '/api/email/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMessagesListRoute = ApiMessagesListRouteImport.update({
  id: '/api/messages/list',
  path: '/api/messages/list',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMessagesOpenRoute = ApiMessagesOpenRouteImport.update({
  id: '/api/messages/open',
  path: '/api/messages/open',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMessagesReplyRoute = ApiMessagesReplyRouteImport.update({
  id: '/api/messages/reply',
  path: '/api/messages/reply',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMessagesSendRoute = ApiMessagesSendRouteImport.update({
  id: '/api/messages/send',
  path: '/api/messages/send',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMessagesThreadRoute = ApiMessagesThreadRouteImport.update({
  id: '/api/messages/thread',
  path: '/api/messages/thread',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPhoneLoginRoute = ApiPhoneLoginRouteImport.update({
  id: '/api/phone/login',
  path: '/api/phone/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPhoneStartRoute = ApiPhoneStartRouteImport.update({
  id: '/api/phone/start',
  path: '/api/phone/start',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSessionEnsureRoute = ApiSessionEnsureRouteImport.update({
  id: '/api/session/ensure',
  path: '/api/session/ensure',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSessionLogoutRoute = ApiSessionLogoutRouteImport.update({
  id: '/api/session/logout',
  path: '/api/session/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSessionTokenRoute = ApiSessionTokenRouteImport.update({
  id: '/api/session/token',
  path: '/api/session/token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/discover': typeof AppDiscoverRoute
  '/feed': typeof AppFeedRoute
  '/inbox': typeof AppInboxRouteWithChildren
  '/likes': typeof AppLikesRoute
  '/me': typeof AppMeRoute
  '/api/app': typeof ApiAppRoute
  '/api/profile': typeof ApiProfileRoute
  '/auth/complete': typeof AuthCompleteRoute
  '/inbox/$id': typeof AppInboxIdRoute
  '/u/$handle': typeof AppUHandleRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/email/login': typeof ApiEmailLoginRoute
  '/api/messages/list': typeof ApiMessagesListRoute
  '/api/messages/open': typeof ApiMessagesOpenRoute
  '/api/messages/reply': typeof ApiMessagesReplyRoute
  '/api/messages/send': typeof ApiMessagesSendRoute
  '/api/messages/thread': typeof ApiMessagesThreadRoute
  '/api/phone/login': typeof ApiPhoneLoginRoute
  '/api/phone/start': typeof ApiPhoneStartRoute
  '/api/session/ensure': typeof ApiSessionEnsureRoute
  '/api/session/logout': typeof ApiSessionLogoutRoute
  '/api/session/token': typeof ApiSessionTokenRoute
  '/inbox/': typeof AppInboxIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/discover': typeof AppDiscoverRoute
  '/feed': typeof AppFeedRoute
  '/likes': typeof AppLikesRoute
  '/me': typeof AppMeRoute
  '/api/app': typeof ApiAppRoute
  '/api/profile': typeof ApiProfileRoute
  '/auth/complete': typeof AuthCompleteRoute
  '/inbox/$id': typeof AppInboxIdRoute
  '/u/$handle': typeof AppUHandleRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/email/login': typeof ApiEmailLoginRoute
  '/api/messages/list': typeof ApiMessagesListRoute
  '/api/messages/open': typeof ApiMessagesOpenRoute
  '/api/messages/reply': typeof ApiMessagesReplyRoute
  '/api/messages/send': typeof ApiMessagesSendRoute
  '/api/messages/thread': typeof ApiMessagesThreadRoute
  '/api/phone/login': typeof ApiPhoneLoginRoute
  '/api/phone/start': typeof ApiPhoneStartRoute
  '/api/session/ensure': typeof ApiSessionEnsureRoute
  '/api/session/logout': typeof ApiSessionLogoutRoute
  '/api/session/token': typeof ApiSessionTokenRoute
  '/inbox': typeof AppInboxIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/_app/discover': typeof AppDiscoverRoute
  '/_app/feed': typeof AppFeedRoute
  '/_app/inbox': typeof AppInboxRouteWithChildren
  '/_app/likes': typeof AppLikesRoute
  '/_app/me': typeof AppMeRoute
  '/api/app': typeof ApiAppRoute
  '/api/profile': typeof ApiProfileRoute
  '/auth/complete': typeof AuthCompleteRoute
  '/_app/inbox/$id': typeof AppInboxIdRoute
  '/_app/u/$handle': typeof AppUHandleRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/email/login': typeof ApiEmailLoginRoute
  '/api/messages/list': typeof ApiMessagesListRoute
  '/api/messages/open': typeof ApiMessagesOpenRoute
  '/api/messages/reply': typeof ApiMessagesReplyRoute
  '/api/messages/send': typeof ApiMessagesSendRoute
  '/api/messages/thread': typeof ApiMessagesThreadRoute
  '/api/phone/login': typeof ApiPhoneLoginRoute
  '/api/phone/start': typeof ApiPhoneStartRoute
  '/api/session/ensure': typeof ApiSessionEnsureRoute
  '/api/session/logout': typeof ApiSessionLogoutRoute
  '/api/session/token': typeof ApiSessionTokenRoute
  '/_app/inbox/': typeof AppInboxIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/onboarding'
    | '/discover'
    | '/feed'
    | '/inbox'
    | '/likes'
    | '/me'
    | '/api/app'
    | '/api/profile'
    | '/auth/complete'
    | '/inbox/$id'
    | '/u/$handle'
    | '/api/auth/$'
    | '/api/email/login'
    | '/api/messages/list'
    | '/api/messages/open'
    | '/api/messages/reply'
    | '/api/messages/send'
    | '/api/messages/thread'
    | '/api/phone/login'
    | '/api/phone/start'
    | '/api/session/ensure'
    | '/api/session/logout'
    | '/api/session/token'
    | '/inbox/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/onboarding'
    | '/discover'
    | '/feed'
    | '/likes'
    | '/me'
    | '/api/app'
    | '/api/profile'
    | '/auth/complete'
    | '/inbox/$id'
    | '/u/$handle'
    | '/api/auth/$'
    | '/api/email/login'
    | '/api/messages/list'
    | '/api/messages/open'
    | '/api/messages/reply'
    | '/api/messages/send'
    | '/api/messages/thread'
    | '/api/phone/login'
    | '/api/phone/start'
    | '/api/session/ensure'
    | '/api/session/logout'
    | '/api/session/token'
    | '/inbox'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/onboarding'
    | '/_app/discover'
    | '/_app/feed'
    | '/_app/inbox'
    | '/_app/likes'
    | '/_app/me'
    | '/api/app'
    | '/api/profile'
    | '/auth/complete'
    | '/_app/inbox/$id'
    | '/_app/u/$handle'
    | '/api/auth/$'
    | '/api/email/login'
    | '/api/messages/list'
    | '/api/messages/open'
    | '/api/messages/reply'
    | '/api/messages/send'
    | '/api/messages/thread'
    | '/api/phone/login'
    | '/api/phone/start'
    | '/api/session/ensure'
    | '/api/session/logout'
    | '/api/session/token'
    | '/_app/inbox/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  ApiAppRoute: typeof ApiAppRoute
  ApiProfileRoute: typeof ApiProfileRoute
  AuthCompleteRoute: typeof AuthCompleteRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiEmailLoginRoute: typeof ApiEmailLoginRoute
  ApiMessagesListRoute: typeof ApiMessagesListRoute
  ApiMessagesOpenRoute: typeof ApiMessagesOpenRoute
  ApiMessagesReplyRoute: typeof ApiMessagesReplyRoute
  ApiMessagesSendRoute: typeof ApiMessagesSendRoute
  ApiMessagesThreadRoute: typeof ApiMessagesThreadRoute
  ApiPhoneLoginRoute: typeof ApiPhoneLoginRoute
  ApiPhoneStartRoute: typeof ApiPhoneStartRoute
  ApiSessionEnsureRoute: typeof ApiSessionEnsureRoute
  ApiSessionLogoutRoute: typeof ApiSessionLogoutRoute
  ApiSessionTokenRoute: typeof ApiSessionTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/discover': {
      id: '/_app/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof AppDiscoverRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/feed': {
      id: '/_app/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof AppFeedRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inbox': {
      id: '/_app/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof AppInboxRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/likes': {
      id: '/_app/likes'
      path: '/likes'
      fullPath: '/likes'
      preLoaderRoute: typeof AppLikesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/me': {
      id: '/_app/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof AppMeRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/app': {
      id: '/api/app'
      path: '/api/app'
      fullPath: '/api/app'
      preLoaderRoute: typeof ApiAppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/profile': {
      id: '/api/profile'
      path: '/api/profile'
      fullPath: '/api/profile'
      preLoaderRoute: typeof ApiProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/complete': {
      id: '/auth/complete'
      path: '/auth/complete'
      fullPath: '/auth/complete'
      preLoaderRoute: typeof AuthCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/inbox/': {
      id: '/_app/inbox/'
      path: '/'
      fullPath: '/inbox/'
      preLoaderRoute: typeof AppInboxIndexRouteImport
      parentRoute: typeof AppInboxRoute
    }
    '/_app/inbox/$id': {
      id: '/_app/inbox/$id'
      path: '/$id'
      fullPath: '/inbox/$id'
      preLoaderRoute: typeof AppInboxIdRouteImport
      parentRoute: typeof AppInboxRoute
    }
    '/_app/u/$handle': {
      id: '/_app/u/$handle'
      path: '/u/$handle'
      fullPath: '/u/$handle'
      preLoaderRoute: typeof AppUHandleRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/email/login': {
      id: '/api/email/login'
      path: '/api/email/login'
      fullPath: '/api/email/login'
      preLoaderRoute: typeof ApiEmailLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/messages/list': {
      id: '/api/messages/list'
      path: '/api/messages/list'
      fullPath: '/api/messages/list'
      preLoaderRoute: typeof ApiMessagesListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/messages/open': {
      id: '/api/messages/open'
      path: '/api/messages/open'
      fullPath: '/api/messages/open'
      preLoaderRoute: typeof ApiMessagesOpenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/messages/reply': {
      id: '/api/messages/reply'
      path: '/api/messages/reply'
      fullPath: '/api/messages/reply'
      preLoaderRoute: typeof ApiMessagesReplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/messages/send': {
      id: '/api/messages/send'
      path: '/api/messages/send'
      fullPath: '/api/messages/send'
      preLoaderRoute: typeof ApiMessagesSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/messages/thread': {
      id: '/api/messages/thread'
      path: '/api/messages/thread'
      fullPath: '/api/messages/thread'
      preLoaderRoute: typeof ApiMessagesThreadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/phone/login': {
      id: '/api/phone/login'
      path: '/api/phone/login'
      fullPath: '/api/phone/login'
      preLoaderRoute: typeof ApiPhoneLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/phone/start': {
      id: '/api/phone/start'
      path: '/api/phone/start'
      fullPath: '/api/phone/start'
      preLoaderRoute: typeof ApiPhoneStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/session/ensure': {
      id: '/api/session/ensure'
      path: '/api/session/ensure'
      fullPath: '/api/session/ensure'
      preLoaderRoute: typeof ApiSessionEnsureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/session/logout': {
      id: '/api/session/logout'
      path: '/api/session/logout'
      fullPath: '/api/session/logout'
      preLoaderRoute: typeof ApiSessionLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/session/token': {
      id: '/api/session/token'
      path: '/api/session/token'
      fullPath: '/api/session/token'
      preLoaderRoute: typeof ApiSessionTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppInboxRouteChildren {
  AppInboxIdRoute: typeof AppInboxIdRoute
  AppInboxIndexRoute: typeof AppInboxIndexRoute
}

const AppInboxRouteChildren: AppInboxRouteChildren = {
  AppInboxIdRoute: AppInboxIdRoute,
  AppInboxIndexRoute: AppInboxIndexRoute,
}

const AppInboxRouteWithChildren = AppInboxRoute._addFileChildren(
  AppInboxRouteChildren,
)

interface AppRouteChildren {
  AppDiscoverRoute: typeof AppDiscoverRoute
  AppFeedRoute: typeof AppFeedRoute
  AppInboxRoute: typeof AppInboxRouteWithChildren
  AppLikesRoute: typeof AppLikesRoute
  AppMeRoute: typeof AppMeRoute
  AppUHandleRoute: typeof AppUHandleRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDiscoverRoute: AppDiscoverRoute,
  AppFeedRoute: AppFeedRoute,
  AppInboxRoute: AppInboxRouteWithChildren,
  AppLikesRoute: AppLikesRoute,
  AppMeRoute: AppMeRoute,
  AppUHandleRoute: AppUHandleRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  ApiAppRoute: ApiAppRoute,
  ApiProfileRoute: ApiProfileRoute,
  AuthCompleteRoute: AuthCompleteRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiEmailLoginRoute: ApiEmailLoginRoute,
  ApiMessagesListRoute: ApiMessagesListRoute,
  ApiMessagesOpenRoute: ApiMessagesOpenRoute,
  ApiMessagesReplyRoute: ApiMessagesReplyRoute,
  ApiMessagesSendRoute: ApiMessagesSendRoute,
  ApiMessagesThreadRoute: ApiMessagesThreadRoute,
  ApiPhoneLoginRoute: ApiPhoneLoginRoute,
  ApiPhoneStartRoute: ApiPhoneStartRoute,
  ApiSessionEnsureRoute: ApiSessionEnsureRoute,
  ApiSessionLogoutRoute: ApiSessionLogoutRoute,
  ApiSessionTokenRoute: ApiSessionTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
