/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AppDiscoverRouteImport } from './routes/_app/discover'
import { Route as AppFeedRouteImport } from './routes/_app/feed'
import { Route as AppInboxRouteImport } from './routes/_app/inbox'
import { Route as AppLikesRouteImport } from './routes/_app/likes'
import { Route as AppMeRouteImport } from './routes/_app/me'
import { Route as AppInboxIndexRouteImport } from './routes/_app/inbox.index'
import { Route as AppInboxIdRouteImport } from './routes/_app/inbox.$id'
import { Route as AppUHandleRouteImport } from './routes/_app/u.$handle'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiPhoneLoginRouteImport } from './routes/api/phone/login'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDiscoverRoute = AppDiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => AppRoute,
} as any)
const AppFeedRoute = AppFeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => AppRoute,
} as any)
const AppInboxRoute = AppInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AppRoute,
} as any)
const AppLikesRoute = AppLikesRouteImport.update({
  id: '/likes',
  path: '/likes',
  getParentRoute: () => AppRoute,
} as any)
const AppMeRoute = AppMeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => AppRoute,
} as any)
const AppInboxIndexRoute = AppInboxIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppInboxRoute,
} as any)
const AppInboxIdRoute = AppInboxIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppInboxRoute,
} as any)
const AppUHandleRoute = AppUHandleRouteImport.update({
  id: '/u/$handle',
  path: '/u/$handle',
  getParentRoute: () => AppRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPhoneLoginRoute = ApiPhoneLoginRouteImport.update({
  id: '/api/phone/login',
  path: '/api/phone/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/discover': typeof AppDiscoverRoute
  '/feed': typeof AppFeedRoute
  '/inbox': typeof AppInboxRouteWithChildren
  '/likes': typeof AppLikesRoute
  '/me': typeof AppMeRoute
  '/inbox/$id': typeof AppInboxIdRoute
  '/u/$handle': typeof AppUHandleRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/phone/login': typeof ApiPhoneLoginRoute
  '/inbox/': typeof AppInboxIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/discover': typeof AppDiscoverRoute
  '/feed': typeof AppFeedRoute
  '/likes': typeof AppLikesRoute
  '/me': typeof AppMeRoute
  '/inbox/$id': typeof AppInboxIdRoute
  '/u/$handle': typeof AppUHandleRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/phone/login': typeof ApiPhoneLoginRoute
  '/inbox': typeof AppInboxIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/_app/discover': typeof AppDiscoverRoute
  '/_app/feed': typeof AppFeedRoute
  '/_app/inbox': typeof AppInboxRouteWithChildren
  '/_app/likes': typeof AppLikesRoute
  '/_app/me': typeof AppMeRoute
  '/_app/inbox/$id': typeof AppInboxIdRoute
  '/_app/u/$handle': typeof AppUHandleRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/phone/login': typeof ApiPhoneLoginRoute
  '/_app/inbox/': typeof AppInboxIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/onboarding'
    | '/discover'
    | '/feed'
    | '/inbox'
    | '/likes'
    | '/me'
    | '/inbox/$id'
    | '/u/$handle'
    | '/api/auth/$'
    | '/api/phone/login'
    | '/inbox/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/onboarding'
    | '/discover'
    | '/feed'
    | '/likes'
    | '/me'
    | '/inbox/$id'
    | '/u/$handle'
    | '/api/auth/$'
    | '/api/phone/login'
    | '/inbox'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/onboarding'
    | '/_app/discover'
    | '/_app/feed'
    | '/_app/inbox'
    | '/_app/likes'
    | '/_app/me'
    | '/_app/inbox/$id'
    | '/_app/u/$handle'
    | '/api/auth/$'
    | '/api/phone/login'
    | '/_app/inbox/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiPhoneLoginRoute: typeof ApiPhoneLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/discover': {
      id: '/_app/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof AppDiscoverRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/feed': {
      id: '/_app/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof AppFeedRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inbox': {
      id: '/_app/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof AppInboxRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/likes': {
      id: '/_app/likes'
      path: '/likes'
      fullPath: '/likes'
      preLoaderRoute: typeof AppLikesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/me': {
      id: '/_app/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof AppMeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inbox/': {
      id: '/_app/inbox/'
      path: '/'
      fullPath: '/inbox/'
      preLoaderRoute: typeof AppInboxIndexRouteImport
      parentRoute: typeof AppInboxRoute
    }
    '/_app/inbox/$id': {
      id: '/_app/inbox/$id'
      path: '/$id'
      fullPath: '/inbox/$id'
      preLoaderRoute: typeof AppInboxIdRouteImport
      parentRoute: typeof AppInboxRoute
    }
    '/_app/u/$handle': {
      id: '/_app/u/$handle'
      path: '/u/$handle'
      fullPath: '/u/$handle'
      preLoaderRoute: typeof AppUHandleRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/phone/login': {
      id: '/api/phone/login'
      path: '/api/phone/login'
      fullPath: '/api/phone/login'
      preLoaderRoute: typeof ApiPhoneLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppInboxRouteChildren {
  AppInboxIdRoute: typeof AppInboxIdRoute
  AppInboxIndexRoute: typeof AppInboxIndexRoute
}

const AppInboxRouteChildren: AppInboxRouteChildren = {
  AppInboxIdRoute: AppInboxIdRoute,
  AppInboxIndexRoute: AppInboxIndexRoute,
}

const AppInboxRouteWithChildren = AppInboxRoute._addFileChildren(
  AppInboxRouteChildren,
)

interface AppRouteChildren {
  AppDiscoverRoute: typeof AppDiscoverRoute
  AppFeedRoute: typeof AppFeedRoute
  AppInboxRoute: typeof AppInboxRouteWithChildren
  AppLikesRoute: typeof AppLikesRoute
  AppMeRoute: typeof AppMeRoute
  AppUHandleRoute: typeof AppUHandleRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDiscoverRoute: AppDiscoverRoute,
  AppFeedRoute: AppFeedRoute,
  AppInboxRoute: AppInboxRouteWithChildren,
  AppLikesRoute: AppLikesRoute,
  AppMeRoute: AppMeRoute,
  AppUHandleRoute: AppUHandleRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiPhoneLoginRoute: ApiPhoneLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
