/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AppDiscoverRouteImport } from './routes/_app/discover'
import { Route as AppFeedRouteImport } from './routes/_app/feed'
import { Route as AppGloryRouteImport } from './routes/_app/glory'
import { Route as AppInboxRouteImport } from './routes/_app/inbox'
import { Route as AppLikesRouteImport } from './routes/_app/likes'
import { Route as AppMeRouteImport } from './routes/_app/me'
import { Route as ApiAccountRouteImport } from './routes/api/account'
import { Route as ApiAdminRouteImport } from './routes/api/admin'
import { Route as ApiAppRouteImport } from './routes/api/app'
import { Route as ApiConfigRouteImport } from './routes/api/config'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiMediaRouteImport } from './routes/api/media'
import { Route as ApiProfileRouteImport } from './routes/api/profile'
import { Route as AuthCompleteRouteImport } from './routes/auth.complete'
import { Route as AppInboxIndexRouteImport } from './routes/_app/inbox.index'
import { Route as AppInboxIdRouteImport } from './routes/_app/inbox.$id'
import { Route as AppUHandleRouteImport } from './routes/_app/u.$handle'
import { Route as ApiAiSelftestRouteImport } from './routes/api/ai/selftest'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiMessagesBotStatusRouteImport } from './routes/api/messages/bot-status'
import { Route as ApiMessagesListRouteImport } from './routes/api/messages/list'
import { Route as ApiMessagesOpenRouteImport } from './routes/api/messages/open'
import { Route as ApiMessagesReplyRouteImport } from './routes/api/messages/reply'
import { Route as ApiMessagesSendRouteImport } from './routes/api/messages/send'
import { Route as ApiMessagesStreamRouteImport } from './routes/api/messages/stream'
import { Route as ApiMessagesThreadRouteImport } from './routes/api/messages/thread'
import { Route as ApiPhoneLoginRouteImport } from './routes/api/phone/login'
import { Route as ApiPhoneStartRouteImport } from './routes/api/phone/start'
import { Route as ApiPhoneStatusRouteImport } from './routes/api/phone/status'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDiscoverRoute = AppDiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => AppRoute,
} as any)
const AppFeedRoute = AppFeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => AppRoute,
} as any)
const AppGloryRoute = AppGloryRouteImport.update({
  id: '/glory',
  path: '/glory',
  getParentRoute: () => AppRoute,
} as any)
const AppInboxRoute = AppInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AppRoute,
} as any)
const AppLikesRoute = AppLikesRouteImport.update({
  id: '/likes',
  path: '/likes',
  getParentRoute: () => AppRoute,
} as any)
const AppMeRoute = AppMeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => AppRoute,
} as any)
const ApiAccountRoute = ApiAccountRouteImport.update({
  id: '/api/account',
  path: '/api/account',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminRoute = ApiAdminRouteImport.update({
  id: '/api/admin',
  path: '/api/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAppRoute = ApiAppRouteImport.update({
  id: '/api/app',
  path: '/api/app',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConfigRoute = ApiConfigRouteImport.update({
  id: '/api/config',
  path: '/api/config',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMediaRoute = ApiMediaRouteImport.update({
  id: '/api/media',
  path: '/api/media',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProfileRoute = ApiProfileRouteImport.update({
  id: '/api/profile',
  path: '/api/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCompleteRoute = AuthCompleteRouteImport.update({
  id: '/auth/complete',
  path: '/auth/complete',
  getParentRoute: () => rootRouteImport,
} as any)
const AppInboxIndexRoute = AppInboxIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppInboxRoute,
} as any)
const AppInboxIdRoute = AppInboxIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppInboxRoute,
} as any)
const AppUHandleRoute = AppUHandleRouteImport.update({
  id: '/u/$handle',
  path: '/u/$handle',
  getParentRoute: () => AppRoute,
} as any)
const ApiAiSelftestRoute = ApiAiSelftestRouteImport.update({
  id: '/api/ai/selftest',
  path: '/api/ai/selftest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMessagesBotStatusRoute = ApiMessagesBotStatusRouteImport.update({
  id: '/api/messages/bot-status',
  path: '/api/messages/bot-status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMessagesListRoute = ApiMessagesListRouteImport.update({
  id: '/api/messages/list',
  path: '/api/messages/list',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMessagesOpenRoute = ApiMessagesOpenRouteImport.update({
  id: '/api/messages/open',
  path: '/api/messages/open',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMessagesReplyRoute = ApiMessagesReplyRouteImport.update({
  id: '/api/messages/reply',
  path: '/api/messages/reply',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMessagesSendRoute = ApiMessagesSendRouteImport.update({
  id: '/api/messages/send',
  path: '/api/messages/send',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMessagesStreamRoute = ApiMessagesStreamRouteImport.update({
  id: '/api/messages/stream',
  path: '/api/messages/stream',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMessagesThreadRoute = ApiMessagesThreadRouteImport.update({
  id: '/api/messages/thread',
  path: '/api/messages/thread',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPhoneLoginRoute = ApiPhoneLoginRouteImport.update({
  id: '/api/phone/login',
  path: '/api/phone/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPhoneStartRoute = ApiPhoneStartRouteImport.update({
  id: '/api/phone/start',
  path: '/api/phone/start',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPhoneStatusRoute = ApiPhoneStatusRouteImport.update({
  id: '/api/phone/status',
  path: '/api/phone/status',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/discover': typeof AppDiscoverRoute
  '/feed': typeof AppFeedRoute
  '/glory': typeof AppGloryRoute
  '/inbox': typeof AppInboxRouteWithChildren
  '/likes': typeof AppLikesRoute
  '/me': typeof AppMeRoute
  '/api/account': typeof ApiAccountRoute
  '/api/admin': typeof ApiAdminRoute
  '/api/app': typeof ApiAppRoute
  '/api/config': typeof ApiConfigRoute
  '/api/health': typeof ApiHealthRoute
  '/api/media': typeof ApiMediaRoute
  '/api/profile': typeof ApiProfileRoute
  '/auth/complete': typeof AuthCompleteRoute
  '/inbox/$id': typeof AppInboxIdRoute
  '/u/$handle': typeof AppUHandleRoute
  '/api/ai/selftest': typeof ApiAiSelftestRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/messages/bot-status': typeof ApiMessagesBotStatusRoute
  '/api/messages/list': typeof ApiMessagesListRoute
  '/api/messages/open': typeof ApiMessagesOpenRoute
  '/api/messages/reply': typeof ApiMessagesReplyRoute
  '/api/messages/send': typeof ApiMessagesSendRoute
  '/api/messages/stream': typeof ApiMessagesStreamRoute
  '/api/messages/thread': typeof ApiMessagesThreadRoute
  '/api/phone/login': typeof ApiPhoneLoginRoute
  '/api/phone/start': typeof ApiPhoneStartRoute
  '/api/phone/status': typeof ApiPhoneStatusRoute
  '/inbox/': typeof AppInboxIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/discover': typeof AppDiscoverRoute
  '/feed': typeof AppFeedRoute
  '/glory': typeof AppGloryRoute
  '/likes': typeof AppLikesRoute
  '/me': typeof AppMeRoute
  '/api/account': typeof ApiAccountRoute
  '/api/admin': typeof ApiAdminRoute
  '/api/app': typeof ApiAppRoute
  '/api/config': typeof ApiConfigRoute
  '/api/health': typeof ApiHealthRoute
  '/api/media': typeof ApiMediaRoute
  '/api/profile': typeof ApiProfileRoute
  '/auth/complete': typeof AuthCompleteRoute
  '/inbox/$id': typeof AppInboxIdRoute
  '/u/$handle': typeof AppUHandleRoute
  '/api/ai/selftest': typeof ApiAiSelftestRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/messages/bot-status': typeof ApiMessagesBotStatusRoute
  '/api/messages/list': typeof ApiMessagesListRoute
  '/api/messages/open': typeof ApiMessagesOpenRoute
  '/api/messages/reply': typeof ApiMessagesReplyRoute
  '/api/messages/send': typeof ApiMessagesSendRoute
  '/api/messages/stream': typeof ApiMessagesStreamRoute
  '/api/messages/thread': typeof ApiMessagesThreadRoute
  '/api/phone/login': typeof ApiPhoneLoginRoute
  '/api/phone/start': typeof ApiPhoneStartRoute
  '/api/phone/status': typeof ApiPhoneStatusRoute
  '/inbox': typeof AppInboxIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/_app/discover': typeof AppDiscoverRoute
  '/_app/feed': typeof AppFeedRoute
  '/_app/glory': typeof AppGloryRoute
  '/_app/inbox': typeof AppInboxRouteWithChildren
  '/_app/likes': typeof AppLikesRoute
  '/_app/me': typeof AppMeRoute
  '/api/account': typeof ApiAccountRoute
  '/api/admin': typeof ApiAdminRoute
  '/api/app': typeof ApiAppRoute
  '/api/config': typeof ApiConfigRoute
  '/api/health': typeof ApiHealthRoute
  '/api/media': typeof ApiMediaRoute
  '/api/profile': typeof ApiProfileRoute
  '/auth/complete': typeof AuthCompleteRoute
  '/_app/inbox/$id': typeof AppInboxIdRoute
  '/_app/u/$handle': typeof AppUHandleRoute
  '/api/ai/selftest': typeof ApiAiSelftestRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/messages/bot-status': typeof ApiMessagesBotStatusRoute
  '/api/messages/list': typeof ApiMessagesListRoute
  '/api/messages/open': typeof ApiMessagesOpenRoute
  '/api/messages/reply': typeof ApiMessagesReplyRoute
  '/api/messages/send': typeof ApiMessagesSendRoute
  '/api/messages/stream': typeof ApiMessagesStreamRoute
  '/api/messages/thread': typeof ApiMessagesThreadRoute
  '/api/phone/login': typeof ApiPhoneLoginRoute
  '/api/phone/start': typeof ApiPhoneStartRoute
  '/api/phone/status': typeof ApiPhoneStatusRoute
  '/_app/inbox/': typeof AppInboxIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/onboarding'
    | '/discover'
    | '/feed'
    | '/glory'
    | '/inbox'
    | '/likes'
    | '/me'
    | '/api/account'
    | '/api/admin'
    | '/api/app'
    | '/api/config'
    | '/api/health'
    | '/api/media'
    | '/api/profile'
    | '/auth/complete'
    | '/inbox/$id'
    | '/u/$handle'
    | '/api/ai/selftest'
    | '/api/auth/$'
    | '/api/messages/bot-status'
    | '/api/messages/list'
    | '/api/messages/open'
    | '/api/messages/reply'
    | '/api/messages/send'
    | '/api/messages/stream'
    | '/api/messages/thread'
    | '/api/phone/login'
    | '/api/phone/start'
    | '/api/phone/status'
    | '/inbox/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/login'
    | '/onboarding'
    | '/discover'
    | '/feed'
    | '/glory'
    | '/likes'
    | '/me'
    | '/api/account'
    | '/api/admin'
    | '/api/app'
    | '/api/config'
    | '/api/health'
    | '/api/media'
    | '/api/profile'
    | '/auth/complete'
    | '/inbox/$id'
    | '/u/$handle'
    | '/api/ai/selftest'
    | '/api/auth/$'
    | '/api/messages/bot-status'
    | '/api/messages/list'
    | '/api/messages/open'
    | '/api/messages/reply'
    | '/api/messages/send'
    | '/api/messages/stream'
    | '/api/messages/thread'
    | '/api/phone/login'
    | '/api/phone/start'
    | '/api/phone/status'
    | '/inbox'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/admin'
    | '/login'
    | '/onboarding'
    | '/_app/discover'
    | '/_app/feed'
    | '/_app/glory'
    | '/_app/inbox'
    | '/_app/likes'
    | '/_app/me'
    | '/api/account'
    | '/api/admin'
    | '/api/app'
    | '/api/config'
    | '/api/health'
    | '/api/media'
    | '/api/profile'
    | '/auth/complete'
    | '/_app/inbox/$id'
    | '/_app/u/$handle'
    | '/api/ai/selftest'
    | '/api/auth/$'
    | '/api/messages/bot-status'
    | '/api/messages/list'
    | '/api/messages/open'
    | '/api/messages/reply'
    | '/api/messages/send'
    | '/api/messages/stream'
    | '/api/messages/thread'
    | '/api/phone/login'
    | '/api/phone/start'
    | '/api/phone/status'
    | '/_app/inbox/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AdminRoute: typeof AdminRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  ApiAccountRoute: typeof ApiAccountRoute
  ApiAdminRoute: typeof ApiAdminRoute
  ApiAppRoute: typeof ApiAppRoute
  ApiConfigRoute: typeof ApiConfigRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiMediaRoute: typeof ApiMediaRoute
  ApiProfileRoute: typeof ApiProfileRoute
  AuthCompleteRoute: typeof AuthCompleteRoute
  ApiAiSelftestRoute: typeof ApiAiSelftestRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiMessagesBotStatusRoute: typeof ApiMessagesBotStatusRoute
  ApiMessagesListRoute: typeof ApiMessagesListRoute
  ApiMessagesOpenRoute: typeof ApiMessagesOpenRoute
  ApiMessagesReplyRoute: typeof ApiMessagesReplyRoute
  ApiMessagesSendRoute: typeof ApiMessagesSendRoute
  ApiMessagesStreamRoute: typeof ApiMessagesStreamRoute
  ApiMessagesThreadRoute: typeof ApiMessagesThreadRoute
  ApiPhoneLoginRoute: typeof ApiPhoneLoginRoute
  ApiPhoneStartRoute: typeof ApiPhoneStartRoute
  ApiPhoneStatusRoute: typeof ApiPhoneStatusRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/discover': {
      id: '/_app/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof AppDiscoverRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/feed': {
      id: '/_app/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof AppFeedRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/glory': {
      id: '/_app/glory'
      path: '/glory'
      fullPath: '/glory'
      preLoaderRoute: typeof AppGloryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inbox': {
      id: '/_app/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof AppInboxRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/likes': {
      id: '/_app/likes'
      path: '/likes'
      fullPath: '/likes'
      preLoaderRoute: typeof AppLikesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/me': {
      id: '/_app/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof AppMeRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/account': {
      id: '/api/account'
      path: '/api/account'
      fullPath: '/api/account'
      preLoaderRoute: typeof ApiAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin': {
      id: '/api/admin'
      path: '/api/admin'
      fullPath: '/api/admin'
      preLoaderRoute: typeof ApiAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/app': {
      id: '/api/app'
      path: '/api/app'
      fullPath: '/api/app'
      preLoaderRoute: typeof ApiAppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/config': {
      id: '/api/config'
      path: '/api/config'
      fullPath: '/api/config'
      preLoaderRoute: typeof ApiConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/media': {
      id: '/api/media'
      path: '/api/media'
      fullPath: '/api/media'
      preLoaderRoute: typeof ApiMediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/profile': {
      id: '/api/profile'
      path: '/api/profile'
      fullPath: '/api/profile'
      preLoaderRoute: typeof ApiProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/complete': {
      id: '/auth/complete'
      path: '/auth/complete'
      fullPath: '/auth/complete'
      preLoaderRoute: typeof AuthCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/inbox/': {
      id: '/_app/inbox/'
      path: '/'
      fullPath: '/inbox/'
      preLoaderRoute: typeof AppInboxIndexRouteImport
      parentRoute: typeof AppInboxRoute
    }
    '/_app/inbox/$id': {
      id: '/_app/inbox/$id'
      path: '/$id'
      fullPath: '/inbox/$id'
      preLoaderRoute: typeof AppInboxIdRouteImport
      parentRoute: typeof AppInboxRoute
    }
    '/_app/u/$handle': {
      id: '/_app/u/$handle'
      path: '/u/$handle'
      fullPath: '/u/$handle'
      preLoaderRoute: typeof AppUHandleRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/ai/selftest': {
      id: '/api/ai/selftest'
      path: '/api/ai/selftest'
      fullPath: '/api/ai/selftest'
      preLoaderRoute: typeof ApiAiSelftestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/messages/bot-status': {
      id: '/api/messages/bot-status'
      path: '/api/messages/bot-status'
      fullPath: '/api/messages/bot-status'
      preLoaderRoute: typeof ApiMessagesBotStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/messages/list': {
      id: '/api/messages/list'
      path: '/api/messages/list'
      fullPath: '/api/messages/list'
      preLoaderRoute: typeof ApiMessagesListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/messages/open': {
      id: '/api/messages/open'
      path: '/api/messages/open'
      fullPath: '/api/messages/open'
      preLoaderRoute: typeof ApiMessagesOpenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/messages/reply': {
      id: '/api/messages/reply'
      path: '/api/messages/reply'
      fullPath: '/api/messages/reply'
      preLoaderRoute: typeof ApiMessagesReplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/messages/send': {
      id: '/api/messages/send'
      path: '/api/messages/send'
      fullPath: '/api/messages/send'
      preLoaderRoute: typeof ApiMessagesSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/messages/stream': {
      id: '/api/messages/stream'
      path: '/api/messages/stream'
      fullPath: '/api/messages/stream'
      preLoaderRoute: typeof ApiMessagesStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/messages/thread': {
      id: '/api/messages/thread'
      path: '/api/messages/thread'
      fullPath: '/api/messages/thread'
      preLoaderRoute: typeof ApiMessagesThreadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/phone/login': {
      id: '/api/phone/login'
      path: '/api/phone/login'
      fullPath: '/api/phone/login'
      preLoaderRoute: typeof ApiPhoneLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/phone/start': {
      id: '/api/phone/start'
      path: '/api/phone/start'
      fullPath: '/api/phone/start'
      preLoaderRoute: typeof ApiPhoneStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/phone/status': {
      id: '/api/phone/status'
      path: '/api/phone/status'
      fullPath: '/api/phone/status'
      preLoaderRoute: typeof ApiPhoneStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppInboxRouteChildren {
  AppInboxIdRoute: typeof AppInboxIdRoute
  AppInboxIndexRoute: typeof AppInboxIndexRoute
}

const AppInboxRouteChildren: AppInboxRouteChildren = {
  AppInboxIdRoute: AppInboxIdRoute,
  AppInboxIndexRoute: AppInboxIndexRoute,
}

const AppInboxRouteWithChildren = AppInboxRoute._addFileChildren(
  AppInboxRouteChildren,
)

interface AppRouteChildren {
  AppDiscoverRoute: typeof AppDiscoverRoute
  AppFeedRoute: typeof AppFeedRoute
  AppGloryRoute: typeof AppGloryRoute
  AppInboxRoute: typeof AppInboxRouteWithChildren
  AppLikesRoute: typeof AppLikesRoute
  AppMeRoute: typeof AppMeRoute
  AppUHandleRoute: typeof AppUHandleRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDiscoverRoute: AppDiscoverRoute,
  AppFeedRoute: AppFeedRoute,
  AppGloryRoute: AppGloryRoute,
  AppInboxRoute: AppInboxRouteWithChildren,
  AppLikesRoute: AppLikesRoute,
  AppMeRoute: AppMeRoute,
  AppUHandleRoute: AppUHandleRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AdminRoute: AdminRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  ApiAccountRoute: ApiAccountRoute,
  ApiAdminRoute: ApiAdminRoute,
  ApiAppRoute: ApiAppRoute,
  ApiConfigRoute: ApiConfigRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiMediaRoute: ApiMediaRoute,
  ApiProfileRoute: ApiProfileRoute,
  AuthCompleteRoute: AuthCompleteRoute,
  ApiAiSelftestRoute: ApiAiSelftestRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiMessagesBotStatusRoute: ApiMessagesBotStatusRoute,
  ApiMessagesListRoute: ApiMessagesListRoute,
  ApiMessagesOpenRoute: ApiMessagesOpenRoute,
  ApiMessagesReplyRoute: ApiMessagesReplyRoute,
  ApiMessagesSendRoute: ApiMessagesSendRoute,
  ApiMessagesStreamRoute: ApiMessagesStreamRoute,
  ApiMessagesThreadRoute: ApiMessagesThreadRoute,
  ApiPhoneLoginRoute: ApiPhoneLoginRoute,
  ApiPhoneStartRoute: ApiPhoneStartRoute,
  ApiPhoneStatusRoute: ApiPhoneStatusRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
